In [1]:
!pip install gensim

Defaulting to user installation because normal site-packages is not writeable
Collecting gensim
  Obtaining dependency information for gensim from https://files.pythonhosted.org/packages/10/c3/7e22d6f7d88c4ea6a3a84481f00538252659d285713c3b7e2e1537b0e7e1/gensim-4.4.0-cp311-cp311-win_amd64.whl.metadata
  Downloading gensim-4.4.0-cp311-cp311-win_amd64.whl.metadata (8.6 kB)
Requirement already satisfied: numpy>=1.18.5 in c:\users\sonup\appdata\roaming\python\python311\site-packages (from gensim) (2.4.6)
Requirement already satisfied: scipy>=1.7.0 in c:\users\sonup\appdata\roaming\python\python311\site-packages (from gensim) (1.17.1)
Collecting smart_open>=1.8.1 (from gensim)
  Obtaining dependency information for smart_open>=1.8.1 from https://files.pythonhosted.org/packages/b4/bd/1c92e69a1daff70118f21e18ef3a100c114f00f08b64a1074484f12d9020/smart_open-8.0.0-py3-none-any.whl.metadata
  Downloading smart_open-8.0.0-py3-none-any.whl.metadata (24 kB)
Collecting wrapt (from smart_open>=1.8.1->gensim)
  Obtaining dependency information for wrapt from https://files.pythonhosted.org/packages/7e/9c/23695baa331c6de4e874c3d78b8e0bed92e1d2a274e665b29858f6841672/wrapt-2.2.2-cp311-cp311-win_amd64.whl.metadata
  Downloading wrapt-2.2.2-cp311-cp311-win_amd64.whl.metadata (7.6 kB)
Downloading gensim-4.4.0-cp311-cp311-win_amd64.whl (24.4 MB)
   ---------------------------------------- 0.0/24.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/24.4 MB 660.6 kB/s eta 0:00:37
   ---------------------------------------- 0.0/24.4 MB 393.8 kB/s eta 0:01:02
   ---------------------------------------- 0.1/24.4 MB 901.1 kB/s eta 0:00:27
   ---------------------------------------- 0.2/24.4 MB 838.4 kB/s eta 0:00:29
   ---------------------------------------- 0.2/24.4 MB 1.1 MB/s eta 0:00:23
    --------------------------------------- 0.3/24.4 MB 1.2 MB/s eta 0:00:21
    --------------------------------------- 0.4/24.4 MB 1.4 MB/s eta 0:00:18
    --------------------------------------- 0.5/24.4 MB 1.5 MB/s eta 0:00:17
   - -------------------------------------- 0.6/24.4 MB 1.5 MB/s eta 0:00:16
   - -------------------------------------- 0.8/24.4 MB 1.7 MB/s eta 0:00:14
   - -------------------------------------- 0.9/24.4 MB 1.9 MB/s eta 0:00:13
   - -------------------------------------- 1.0/24.4 MB 1.9 MB/s eta 0:00:12
   - -------------------------------------- 1.0/24.4 MB 1.9 MB/s eta 0:00:12
   - -------------------------------------- 1.0/24.4 MB 1.9 MB/s eta 0:00:12
   - -------------------------------------- 1.1/24.4 MB 1.6 MB/s eta 0:00:15
   - -------------------------------------- 1.2/24.4 MB 1.6 MB/s eta 0:00:15
   -- ------------------------------------- 1.4/24.4 MB 1.8 MB/s eta 0:00:13
   -- ------------------------------------- 1.6/24.4 MB 1.9 MB/s eta 0:00:13
   -- ------------------------------------- 1.8/24.4 MB 2.0 MB/s eta 0:00:12
   --- ------------------------------------ 2.0/24.4 MB 2.1 MB/s eta 0:00:11
   --- ------------------------------------ 2.1/24.4 MB 2.1 MB/s eta 0:00:11
   --- ------------------------------------ 2.1/24.4 MB 2.1 MB/s eta 0:00:11
   --- ------------------------------------ 2.1/24.4 MB 2.1 MB/s eta 0:00:11
   --- ------------------------------------ 2.3/24.4 MB 2.0 MB/s eta 0:00:12
   ---- ----------------------------------- 2.6/24.4 MB 2.1 MB/s eta 0:00:11
   ---- ----------------------------------- 2.8/24.4 MB 2.2 MB/s eta 0:00:10
   ---- ----------------------------------- 3.0/24.4 MB 2.3 MB/s eta 0:00:10
   ----- ---------------------------------- 3.3/24.4 MB 2.4 MB/s eta 0:00:09
   ----- ---------------------------------- 3.6/24.4 MB 2.5 MB/s eta 0:00:09
   ------ --------------------------------- 3.8/24.4 MB 2.6 MB/s eta 0:00:08
   ------ --------------------------------- 4.0/24.4 MB 2.7 MB/s eta 0:00:08
   ------- -------------------------------- 4.3/24.4 MB 2.8 MB/s eta 0:00:08
   ------- -------------------------------- 4.6/24.4 MB 2.9 MB/s eta 0:00:07
   ------- -------------------------------- 4.9/24.4 MB 3.0 MB/s eta 0:00:07
   -------- ------------------------------- 5.1/24.4 MB 3.1 MB/s eta 0:00:07
   -------- ------------------------------- 5.2/24.4 MB 3.0 MB/s eta 0:00:07
   -------- ------------------------------- 5.4/24.4 MB 3.1 MB/s eta 0:00:07
   --------- ------------------------------ 5.6/24.4 MB 3.1 MB/s eta 0:00:07
   --------- ------------------------------ 5.8/24.4 MB 3.1 MB/s eta 0:00:06
   --------- ------------------------------ 6.1/24.4 MB 3.2 MB/s eta 0:00:06
   ---------- ----------------------------- 6.3/24.4 MB 3.2 MB/s eta 0:00:06
   ---------- ----------------------------- 6.5/24.4 MB 3.3 MB/s eta 0:00:06
   ----------- ---------------------------- 6.8/24.4 MB 3.3 MB/s eta 0:00:06
   ----------- ---------------------------- 7.0/24.4 MB 3.4 MB/s eta 0:00:06
   ----------- ---------------------------- 7.3/24.4 MB 3.4 MB/s eta 0:00:06
   ------------ --------------------------- 7.3/24.4 MB 3.4 MB/s eta 0:00:05
   ------------ --------------------------- 7.3/24.4 MB 3.4 MB/s eta 0:00:05
   ------------ --------------------------- 7.3/24.4 MB 3.4 MB/s eta 0:00:05
   ------------ --------------------------- 7.6/24.4 MB 3.3 MB/s eta 0:00:06
   ------------ --------------------------- 7.9/24.4 MB 3.3 MB/s eta 0:00:06
   ------------- -------------------------- 8.1/24.4 MB 3.4 MB/s eta 0:00:05
   ------------- -------------------------- 8.4/24.4 MB 3.4 MB/s eta 0:00:05
   -------------- ------------------------- 8.7/24.4 MB 3.5 MB/s eta 0:00:05
   -------------- ------------------------- 9.0/24.4 MB 3.5 MB/s eta 0:00:05
   --------------- ------------------------ 9.3/24.4 MB 3.6 MB/s eta 0:00:05
   --------------- ------------------------ 9.6/24.4 MB 3.6 MB/s eta 0:00:05
   ---------------- ----------------------- 9.9/24.4 MB 3.7 MB/s eta 0:00:04
   ---------------- ----------------------- 10.2/24.4 MB 3.7 MB/s eta 0:00:04
   ----------------- ---------------------- 10.5/24.4 MB 4.0 MB/s eta 0:00:04
   ----------------- ---------------------- 10.8/24.4 MB 4.1 MB/s eta 0:00:04
   ------------------ --------------------- 11.0/24.4 MB 4.2 MB/s eta 0:00:04
   ------------------ --------------------- 11.3/24.4 MB 4.6 MB/s eta 0:00:03
   ------------------- -------------------- 11.6/24.4 MB 4.6 MB/s eta 0:00:03
   ------------------- -------------------- 11.9/24.4 MB 4.7 MB/s eta 0:00:03
   -------------------- ------------------- 12.2/24.4 MB 4.9 MB/s eta 0:00:03
   -------------------- ------------------- 12.5/24.4 MB 5.2 MB/s eta 0:00:03
   -------------------- ------------------- 12.6/24.4 MB 5.2 MB/s eta 0:00:03
   -------------------- ------------------- 12.7/24.4 MB 5.1 MB/s eta 0:00:03
   --------------------- ------------------ 13.1/24.4 MB 5.2 MB/s eta 0:00:03
   --------------------- ------------------ 13.3/24.4 MB 5.2 MB/s eta 0:00:03
   ---------------------- ----------------- 13.5/24.4 MB 5.2 MB/s eta 0:00:03
   ---------------------- ----------------- 13.6/24.4 MB 5.1 MB/s eta 0:00:03
   ---------------------- ----------------- 13.9/24.4 MB 5.0 MB/s eta 0:00:03
   ----------------------- ---------------- 14.2/24.4 MB 5.1 MB/s eta 0:00:03
   ----------------------- ---------------- 14.2/24.4 MB 5.0 MB/s eta 0:00:03
   ----------------------- ---------------- 14.5/24.4 MB 5.0 MB/s eta 0:00:02
   ------------------------ --------------- 14.7/24.4 MB 5.0 MB/s eta 0:00:02
   ------------------------ --------------- 14.7/24.4 MB 5.0 MB/s eta 0:00:02
   ------------------------ --------------- 14.8/24.4 MB 4.7 MB/s eta 0:00:03
   ------------------------ --------------- 15.2/24.4 MB 4.7 MB/s eta 0:00:02
   ------------------------- -------------- 15.6/24.4 MB 4.9 MB/s eta 0:00:02
   ------------------------- -------------- 15.7/24.4 MB 4.9 MB/s eta 0:00:02
   -------------------------- ------------- 15.9/24.4 MB 4.8 MB/s eta 0:00:02
   -------------------------- ------------- 16.2/24.4 MB 4.8 MB/s eta 0:00:02
   --------------------------- ------------ 16.5/24.4 MB 4.9 MB/s eta 0:00:02
   --------------------------- ------------ 16.8/24.4 MB 4.9 MB/s eta 0:00:02
   ---------------------------- ----------- 17.1/24.4 MB 4.9 MB/s eta 0:00:02
   ---------------------------- ----------- 17.5/24.4 MB 5.0 MB/s eta 0:00:02
   ---------------------------- ----------- 17.5/24.4 MB 4.9 MB/s eta 0:00:02
   ----------------------------- ---------- 17.8/24.4 MB 5.2 MB/s eta 0:00:02
   ----------------------------- ---------- 18.0/24.4 MB 5.2 MB/s eta 0:00:02
   ------------------------------ --------- 18.4/24.4 MB 5.2 MB/s eta 0:00:02
   ------------------------------ --------- 18.7/24.4 MB 5.2 MB/s eta 0:00:02
   ------------------------------ --------- 18.7/24.4 MB 5.2 MB/s eta 0:00:02
   ------------------------------- -------- 19.0/24.4 MB 5.1 MB/s eta 0:00:02
   ------------------------------- -------- 19.3/24.4 MB 5.1 MB/s eta 0:00:02
   -------------------------------- ------- 19.7/24.4 MB 5.2 MB/s eta 0:00:01
   -------------------------------- ------- 19.9/24.4 MB 5.0 MB/s eta 0:00:01
   --------------------------------- ------ 20.1/24.4 MB 5.0 MB/s eta 0:00:01
   --------------------------------- ------ 20.6/24.4 MB 5.0 MB/s eta 0:00:01
   ---------------------------------- ----- 21.0/24.4 MB 5.0 MB/s eta 0:00:01
   ---------------------------------- ----- 21.3/24.4 MB 5.0 MB/s eta 0:00:01
   ----------------------------------- ---- 21.7/24.4 MB 5.0 MB/s eta 0:00:01
   ------------------------------------ --- 22.0/24.4 MB 5.0 MB/s eta 0:00:01
   ------------------------------------ --- 22.0/24.4 MB 5.0 MB/s eta 0:00:01
   ------------------------------------ --- 22.0/24.4 MB 5.0 MB/s eta 0:00:01
   ------------------------------------ --- 22.1/24.4 MB 4.7 MB/s eta 0:00:01
   ------------------------------------ --- 22.4/24.4 MB 4.7 MB/s eta 0:00:01
   ------------------------------------- -- 22.7/24.4 MB 4.7 MB/s eta 0:00:01
   ------------------------------------- -- 23.1/24.4 MB 4.9 MB/s eta 0:00:01
   -------------------------------------- - 23.3/24.4 MB 4.9 MB/s eta 0:00:01
   -------------------------------------- - 23.5/24.4 MB 4.9 MB/s eta 0:00:01
   -------------------------------------- - 23.8/24.4 MB 4.8 MB/s eta 0:00:01
   ---------------------------------------  24.1/24.4 MB 5.0 MB/s eta 0:00:01
   ---------------------------------------  24.4/24.4 MB 5.0 MB/s eta 0:00:01
   ---------------------------------------  24.4/24.4 MB 5.0 MB/s eta 0:00:01
   ---------------------------------------- 24.4/24.4 MB 4.8 MB/s eta 0:00:00
Downloading smart_open-8.0.0-py3-none-any.whl (73 kB)
   ---------------------------------------- 0.0/73.0 kB ? eta -:--:--
   ---------------------------------------- 73.0/73.0 kB 3.9 MB/s eta 0:00:00
Downloading wrapt-2.2.2-cp311-cp311-win_amd64.whl (80 kB)
   ---------------------------------------- 0.0/80.4 kB ? eta -:--:--
   ---------------------------------------- 80.4/80.4 kB 2.3 MB/s eta 0:00:00
Installing collected packages: wrapt, smart_open, gensim
Successfully installed gensim-4.4.0 smart_open-8.0.0 wrapt-2.2.2

[notice] A new release of pip is available: 23.2.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import gensim

In [2]:
from gensim.models import Word2Vec, KeyedVectors

In [5]:
import gensim.downloader as api
wv = api.load('word2vec-google-news-300')
vec_king = wv['king']

[==================================================] 100.0% 1662.8/1662.8MB downloaded

In [6]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  2.01416016e-02, -1.63085938e-01,  1.35803223e-03,
       -1.44531250e-01, -5.68847656e-02,  4.29687500e-02, -2.46582031e-02,
        1.85546875e-01,  4.47265625e-01,  9.58251953e-03,  1.31835938e-01,
        9.86328125e-02, -1.85546875e-01, -1.00097656e-01, -1.33789062e-01,
       -1.25000000e-01,  2.83203125e-01,  1.23046875e-01,  5.32226562e-02,
       -1.77734375e-01,  8.59375000e-02, -2.18505859e-02,  2.05078125e-02,
       -1.39648438e-01,  2.51464844e-02,  1.38671875e-01, -1.05468750e-01,
        1.38671875e-01,  8.88671875e-02, -7.51953125e-02, -2.13623047e-02,
        1.72851562e-01,  4.63867188e-02, -2.65625000e-01,  8.91113281e-03,
        1.49414062e-01,  3.78417969e-02,  2.38281250e-01, -1.24511719e-01,
       -2.17773438e-01, -1.81640625e-01,  2.97851562e-02,  5.71289062e-02,
       -2.89306641e-02,  1.24511719e-02,  9.66796875e-02, -2.31445312e-01,
        5.81054688e-02,  6.68945312e-02,  7.08007812e-02, -3.08593750e-01,
       -2.14843750e-01,  1.45507812e-01, -4.27734375e-01, -9.39941406e-03,
        1.54296875e-01, -7.66601562e-02,  2.89062500e-01,  2.77343750e-01,
       -4.86373901e-04, -1.36718750e-01,  3.24218750e-01, -2.46093750e-01,
       -3.03649902e-03, -2.11914062e-01,  1.25000000e-01,  2.69531250e-01,
        2.04101562e-01,  8.25195312e-02, -2.01171875e-01, -1.60156250e-01,
       -3.78417969e-02, -1.20117188e-01,  1.15234375e-01, -4.10156250e-02,
       -3.95507812e-02, -8.98437500e-02,  6.34765625e-03,  2.03125000e-01,
        1.86523438e-01,  2.73437500e-01,  6.29882812e-02,  1.41601562e-01,
       -9.81445312e-02,  1.38671875e-01,  1.82617188e-01,  1.73828125e-01,
        1.73828125e-01, -2.37304688e-01,  1.78710938e-01,  6.34765625e-02,
        2.36328125e-01, -2.08984375e-01,  8.74023438e-02, -1.66015625e-01,
       -7.91015625e-02,  2.43164062e-01, -8.88671875e-02,  1.26953125e-01,
       -2.16796875e-01, -1.73828125e-01, -3.59375000e-01, -8.25195312e-02,
       -6.49414062e-02,  5.07812500e-02,  1.35742188e-01, -7.47070312e-02,
       -1.64062500e-01,  1.15356445e-02,  4.45312500e-01, -2.15820312e-01,
       -1.11328125e-01, -1.92382812e-01,  1.70898438e-01, -1.25000000e-01,
        2.65502930e-03,  1.92382812e-01, -1.74804688e-01,  1.39648438e-01,
        2.92968750e-01,  1.13281250e-01,  5.95703125e-02, -6.39648438e-02,
        9.96093750e-02, -2.72216797e-02,  1.96533203e-02,  4.27246094e-02,
       -2.46093750e-01,  6.39648438e-02, -2.25585938e-01, -1.68945312e-01,
        2.89916992e-03,  8.20312500e-02,  3.41796875e-01,  4.32128906e-02,
        1.32812500e-01,  1.42578125e-01,  7.61718750e-02,  5.98144531e-02,
       -1.19140625e-01,  2.74658203e-03, -6.29882812e-02, -2.72216797e-02,
       -4.82177734e-03, -8.20312500e-02, -2.49023438e-02, -4.00390625e-01,
       -1.06933594e-01,  4.24804688e-02,  7.76367188e-02, -1.16699219e-01,
        7.37304688e-02, -9.22851562e-02,  1.07910156e-01,  1.58203125e-01,
        4.24804688e-02,  1.26953125e-01,  3.61328125e-02,  2.67578125e-01,
       -1.01074219e-01, -3.02734375e-01, -5.76171875e-02,  5.05371094e-02,
        5.26428223e-04, -2.07031250e-01, -1.38671875e-01, -8.97216797e-03,
       -2.78320312e-02, -1.41601562e-01,  2.07031250e-01, -1.58203125e-01,
        1.27929688e-01,  1.49414062e-01, -2.24609375e-02, -8.44726562e-02,
        1.22558594e-01,  2.15820312e-01, -2.13867188e-01, -3.12500000e-01,
       -3.73046875e-01,  4.08935547e-03,  1.07421875e-01,  1.06933594e-01,
        7.32421875e-02,  8.97216797e-03, -3.88183594e-02, -1.29882812e-01,
        1.49414062e-01, -2.14843750e-01, -1.83868408e-03,  9.91210938e-02,
        1.57226562e-01, -1.14257812e-01, -2.05078125e-01,  9.91210938e-02,
        3.69140625e-01, -1.97265625e-01,  3.54003906e-02,  1.09375000e-01,
        1.31835938e-01,  1.66992188e-01,  2.35351562e-01,  1.04980469e-01,
       -4.96093750e-01, -1.64062500e-01, -1.56250000e-01, -5.22460938e-02,
        1.03027344e-01,  2.43164062e-01, -1.88476562e-01,  5.07812500e-02,
       -9.37500000e-02, -6.68945312e-02,  2.27050781e-02,  7.61718750e-02,
        2.89062500e-01,  3.10546875e-01, -5.37109375e-02,  2.28515625e-01,
        2.51464844e-02,  6.78710938e-02, -1.21093750e-01, -2.15820312e-01,
       -2.73437500e-01, -3.07617188e-02, -3.37890625e-01,  1.53320312e-01,
        2.33398438e-01, -2.08007812e-01,  3.73046875e-01,  8.20312500e-02,
        2.51953125e-01, -7.61718750e-02, -4.66308594e-02, -2.23388672e-02,
        2.99072266e-02, -5.93261719e-02, -4.66918945e-03, -2.44140625e-01,
       -2.09960938e-01, -2.87109375e-01, -4.54101562e-02, -1.77734375e-01,
       -2.79296875e-01, -8.59375000e-02,  9.13085938e-02,  2.51953125e-01],
      dtype=float32)

In [7]:
vec_king.shape

(300,)

In [8]:
wv['cricket']

array([-3.67187500e-01, -1.21582031e-01,  2.85156250e-01,  8.15429688e-02,
        3.19824219e-02, -3.19824219e-02,  1.34765625e-01, -2.73437500e-01,
        9.46044922e-03, -1.07421875e-01,  2.48046875e-01, -6.05468750e-01,
        5.02929688e-02,  2.98828125e-01,  9.57031250e-02,  1.39648438e-01,
       -5.41992188e-02,  2.91015625e-01,  2.85156250e-01,  1.51367188e-01,
       -2.89062500e-01, -3.46679688e-02,  1.81884766e-02, -3.92578125e-01,
        2.46093750e-01,  2.51953125e-01, -9.86328125e-02,  3.22265625e-01,
        4.49218750e-01, -1.36718750e-01, -2.34375000e-01,  4.12597656e-02,
       -2.15820312e-01,  1.69921875e-01,  2.56347656e-02,  1.50146484e-02,
       -3.75976562e-02,  6.95800781e-03,  4.00390625e-01,  2.09960938e-01,
        1.17675781e-01, -4.19921875e-02,  2.34375000e-01,  2.03125000e-01,
       -1.86523438e-01, -2.46093750e-01,  3.12500000e-01, -2.59765625e-01,
       -1.06933594e-01,  1.04003906e-01, -1.79687500e-01,  5.71289062e-02,
       -7.41577148e-03, -5.59082031e-02,  7.61718750e-02, -4.14062500e-01,
       -3.65234375e-01, -3.35937500e-01, -1.54296875e-01, -2.39257812e-01,
       -3.73046875e-01,  2.27355957e-03, -3.51562500e-01,  8.64257812e-02,
        1.26953125e-01,  2.21679688e-01, -9.86328125e-02,  1.08886719e-01,
        3.65234375e-01, -5.66406250e-02,  5.66406250e-02, -1.09375000e-01,
       -1.66992188e-01, -4.54101562e-02, -2.00195312e-01, -1.22558594e-01,
        1.31835938e-01, -1.31835938e-01,  1.03027344e-01, -3.41796875e-01,
       -1.57226562e-01,  2.04101562e-01,  4.39453125e-02,  2.44140625e-01,
       -3.19824219e-02,  3.20312500e-01, -4.41894531e-02,  1.08398438e-01,
       -4.98046875e-02, -9.52148438e-03,  2.46093750e-01, -5.59082031e-02,
        4.07714844e-02, -1.78222656e-02, -2.95410156e-02,  1.65039062e-01,
        5.03906250e-01, -2.81250000e-01,  9.81445312e-02,  1.80664062e-02,
       -1.83593750e-01,  2.53906250e-01,  2.25585938e-01,  1.63574219e-02,
        1.81640625e-01,  1.38671875e-01,  3.33984375e-01,  1.39648438e-01,
        1.45874023e-02, -2.89306641e-02, -8.39843750e-02,  1.50390625e-01,
        1.67968750e-01,  2.28515625e-01,  3.59375000e-01,  1.22558594e-01,
       -3.28125000e-01, -1.56250000e-01,  2.77343750e-01,  1.77001953e-02,
       -1.46484375e-01, -4.51660156e-03, -4.46777344e-02,  1.75781250e-01,
       -3.75000000e-01,  1.16699219e-01, -1.39648438e-01,  2.55859375e-01,
       -1.96289062e-01, -2.57568359e-02, -5.41992188e-02, -2.51464844e-02,
       -1.93359375e-01, -3.17382812e-02, -8.74023438e-02, -1.32812500e-01,
       -2.12402344e-02,  4.33593750e-01, -5.20019531e-02,  3.46679688e-02,
        8.00781250e-02,  3.41796875e-02,  1.99218750e-01, -2.39257812e-02,
       -2.37304688e-01,  1.93359375e-01,  7.32421875e-02, -2.87109375e-01,
        1.25000000e-01,  8.44726562e-02,  1.30859375e-01, -2.19726562e-01,
       -1.61132812e-01, -2.63671875e-01, -5.46875000e-01, -2.96875000e-01,
        3.44238281e-02, -2.87109375e-01, -1.93359375e-01, -1.61132812e-01,
       -3.84765625e-01, -2.14843750e-01, -6.22558594e-03, -1.27929688e-01,
       -1.00097656e-01, -6.21093750e-01,  3.78906250e-01, -4.58984375e-01,
        1.44531250e-01, -9.13085938e-02, -3.08593750e-01,  2.23632812e-01,
        7.86132812e-02, -2.16796875e-01,  8.78906250e-02, -1.66992188e-01,
        1.14746094e-02, -2.53906250e-01, -6.25000000e-02,  6.04248047e-03,
        1.56250000e-01,  4.37500000e-01, -2.23632812e-01, -2.32421875e-01,
        2.75390625e-01,  2.39257812e-01,  4.49218750e-02, -7.51953125e-02,
        5.74218750e-01, -2.61230469e-02, -1.21582031e-01,  2.44140625e-01,
       -3.37890625e-01,  8.59375000e-02, -7.71484375e-02,  4.85839844e-02,
        1.43554688e-01,  4.25781250e-01, -4.29687500e-02, -1.08398438e-01,
        1.19628906e-01, -1.91406250e-01, -2.12890625e-01, -2.87109375e-01,
       -1.14746094e-01, -2.04101562e-01, -2.06298828e-02, -2.53906250e-01,
        8.25195312e-02, -3.97949219e-02, -1.57226562e-01,  1.34765625e-01,
        2.08007812e-01, -1.78710938e-01, -2.00195312e-02, -8.34960938e-02,
       -1.20605469e-01,  4.29687500e-02, -1.94335938e-01, -1.32812500e-01,
       -2.17285156e-02, -2.35351562e-01, -3.63281250e-01,  1.51367188e-01,
        9.32617188e-02,  1.63085938e-01,  1.02050781e-01, -4.27734375e-01,
        2.83203125e-01,  2.74658203e-04, -3.20312500e-01,  1.68457031e-02,
        4.06250000e-01, -5.24902344e-02,  7.91015625e-02, -1.41601562e-01,
        5.27343750e-01, -1.26953125e-01,  4.74609375e-01, -6.64062500e-02,
        3.41796875e-01, -1.78710938e-01,  3.69140625e-01, -2.05078125e-01,
        5.82885742e-03, -1.84570312e-01, -8.88671875e-02, -1.81640625e-01,
       -4.80957031e-02,  4.39453125e-01,  2.12890625e-01, -3.07617188e-02,
        9.32617188e-02,  2.40234375e-01,  2.39257812e-01,  2.51953125e-01,
       -1.98974609e-02,  1.24511719e-01, -4.73632812e-02, -2.13623047e-02,
        3.12500000e-02,  3.05175781e-02,  2.79296875e-01,  9.08203125e-02,
       -2.02148438e-01, -2.19726562e-02, -2.63671875e-01,  8.78906250e-02,
       -1.07421875e-01, -2.49023438e-01, -1.22070312e-02,  1.73828125e-01,
       -9.91210938e-02,  7.27539062e-02,  2.59765625e-01, -4.60937500e-01,
        3.59375000e-01, -2.25585938e-01,  1.87988281e-02, -2.19726562e-01,
       -2.08984375e-01, -1.51367188e-01,  8.64257812e-02,  1.11694336e-02,
        6.93359375e-02, -2.99072266e-02,  1.43554688e-01,  1.89453125e-01,
       -1.32812500e-01,  4.72656250e-01, -1.40625000e-01, -2.52685547e-02,
        1.91406250e-01, -2.63671875e-01, -1.39648438e-01,  1.09375000e-01,
        1.97753906e-02,  2.49023438e-01, -1.42578125e-01,  4.15039062e-02],
      dtype=float32)

In [9]:
wv.most_similar('cricket')

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783)]

In [10]:
wv.most_similar('happy')

[('glad', 0.7408890724182129),
 ('pleased', 0.6632170677185059),
 ('ecstatic', 0.6626912355422974),
 ('overjoyed', 0.6599286794662476),
 ('thrilled', 0.6514049172401428),
 ('satisfied', 0.6437949538230896),
 ('proud', 0.636042058467865),
 ('delighted', 0.627237856388092),
 ('disappointed', 0.6269949674606323),
 ('excited', 0.6247665286064148)]

In [11]:
wv.similarity("hockey","sports")

np.float32(0.5354152)

In [12]:
vec=wv['king']-wv['man']+wv['women']

In [13]:
vec

array([-0.33984375,  0.06298828, -0.00994873,  0.3305664 ,  0.10327148,
       -0.25854492,  0.19677734, -0.32476807, -0.15917969,  0.45752716,
       -0.39208984, -0.22460938,  0.02929688,  0.31982422, -0.0958252 ,
       -0.05932617,  0.01855469, -0.03945923,  0.01101685,  0.33984375,
        0.10351562,  0.14396667, -0.07641602,  0.06640625, -0.10839844,
       -0.1953125 , -0.3564453 , -0.02124023, -0.16503906, -0.16247559,
       -0.05519104, -0.1003418 ,  0.01464844,  0.23449707, -0.26611328,
       -0.07080078, -0.26904297, -0.00292969, -0.06738281, -0.02050781,
        0.04418945, -0.09326172,  0.12304688,  0.10626221,  0.10290527,
        0.01660156, -0.10791016, -0.0065918 ,  0.17578125,  0.10028076,
        0.22363281, -0.05761719, -0.31743622,  0.3922119 , -0.35498047,
       -0.23643494, -0.01074219, -0.01334572, -0.15283203, -0.00793457,
        0.08203125,  0.09985352,  0.003479  ,  0.11608887,  0.14550781,
       -0.125     , -0.11254883,  0.2548828 , -0.04345703,  0.34985352,
       -0.02880859,  0.15966797,  0.07226562,  0.17626953,  0.15979004,
       -0.20263672, -0.23864746,  0.3400879 ,  0.17700195,  0.15454102,
       -0.20385742,  0.05224609, -0.05224609,  0.3067627 , -0.14892578,
       -0.07910156, -0.10107422,  0.06176758,  0.08154297,  0.17700195,
        0.04589844, -0.41674805, -0.32019043, -0.16674805,  0.11083984,
       -0.02352905,  0.35290527, -0.30004883,  0.25634766, -0.16748047,
        0.21386719,  0.12304688, -0.27490234, -0.35009766, -0.4580078 ,
        0.38671875, -0.6265869 , -0.13139915,  0.34692383,  0.11553955,
        0.42016602,  0.32763672, -0.03381157,  0.08630371,  0.2419281 ,
       -0.35412598,  0.19325256, -0.36791992,  0.17056274,  0.1459961 ,
       -0.18945312,  0.28393555,  0.01953125, -0.18115234,  0.08374023,
       -0.01483154,  0.06591797,  0.21643066, -0.01757812,  0.18481445,
        0.01757812,  0.07226562,  0.01220703,  0.4343872 ,  0.2734375 ,
        0.20452881,  0.01586914,  0.01391602,  0.33740234, -0.30273438,
       -0.00439453, -0.5595703 ,  0.38867188, -0.1373291 ,  0.13574219,
       -0.20605469,  0.10742188,  0.02148438, -0.14648438,  0.2142334 ,
       -0.06054688,  0.23291016, -0.16430664, -0.4741211 , -0.13745117,
       -0.12353516, -0.26293945,  0.03125   ,  0.15332031, -0.08251953,
       -0.11865234, -0.10687256,  0.2421875 , -0.11425781, -0.05310059,
       -0.30371094, -0.06225586,  0.05029297, -0.07272339,  0.11499023,
       -0.2980957 ,  0.09692383,  0.41088867,  0.16601562,  0.3486328 ,
       -0.17211914,  0.33325195, -0.19030762,  0.14611816,  0.14916992,
       -0.33129883, -0.11791992, -0.39538574, -0.13183594, -0.07034302,
        0.03204346,  0.38623047, -0.07495117,  0.15112305,  0.38134766,
        0.2423706 , -0.11083984, -0.109375  , -0.08319092, -0.1003418 ,
        0.08483887,  0.34039307,  0.11035156,  0.01074219, -0.3815918 ,
       -0.1743164 ,  0.14331055,  0.2562256 , -0.2944336 ,  0.00488281,
       -0.04443359, -0.06347656,  0.03100586, -0.12084961,  0.41137695,
        0.078125  ,  0.34484863, -0.05615234, -0.2998047 ,  0.06054688,
        0.17797852, -0.01876068, -0.16064453,  0.09765625, -0.05682373,
       -0.2878418 , -0.05664062,  0.19726562, -0.22753906,  0.00268555,
       -0.17297363, -0.19726562, -0.15332031,  0.1899414 ,  0.32299805,
       -0.18261719, -0.06103516, -0.47460938,  0.1251831 ,  0.08056641,
       -0.05444336,  0.17797852,  0.00754547, -0.00805664, -0.18371582,
        0.23339844, -0.39074707,  0.18608856,  0.12158203,  0.2767334 ,
       -0.06054688, -0.28857422,  0.3359375 , -0.02954102, -0.12329102,
        0.09594727,  0.1965332 ,  0.15771484, -0.015625  ,  0.20019531,
       -0.07763672, -0.30419922, -0.21777344,  0.06689453,  0.11193848,
       -0.03125   ,  0.17773438, -0.05078125,  0.15014648, -0.19580078,
       -0.2319336 , -0.04980469,  0.16308594,  0.4963379 ,  0.64746094,
        0.03808594,  0.5743408 , -0.1274414 ,  0.16711426,  0.12188721,
       -0.43432617, -0.3585205 , -0.12646484, -0.04003906,  0.39794922,
        0.25683594, -0.45654297,  0.3178711 , -0.24658203,  0.16040039,
       -0.11010742, -0.14331055, -0.0291748 ,  0.02893066, -0.03295898,
       -0.05691528, -0.11279297, -0.18359375, -0.4482422 , -0.00830078,
       -0.12371826, -0.02783203,  0.26367188,  0.27148438,  0.28808594],
      dtype=float32)

In [14]:
wv.most_similar([vec])

[('king', 0.6478992700576782),
 ('queen', 0.535493791103363),
 ('women', 0.5233659148216248),
 ('kings', 0.5162314772605896),
 ('queens', 0.4995364248752594),
 ('kumaris', 0.49238473176956177),
 ('princes', 0.46233269572257996),
 ('monarch', 0.45280295610427856),
 ('monarchy', 0.4293173849582672),
 ('kings_princes', 0.42342400550842285)]

In [3]:
import pandas as pd
messages=pd.read_csv('SMSSpamCollection.csv', sep=',',names=["label","message"])

In [4]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

In [5]:
## Data cleaning and preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\sonup\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [6]:
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-Z]',' ',messages['message'][i])
    review=review.lower()
    review=review.split()
    review = [lemmatizer.lemmatize(word) for word in review]
    review=' '.join(review)
    corpus.append(review)

In [49]:
[[i,j,k] for i,j,k in zip(list(map(len,corpus)),corpus,messages['message']) if i<1]

[]

In [7]:
corpus

['go until jurong point crazy available only in bugis n great world la',
 'ok lar joking wif u oni',
 'free entry in a wkly comp to win fa cup final ticket text win to now',
 'u dun say so early hor u c already then say',
 'nah i don t think he go to usf he life around here though',
 'freemsg hey there darling it s been week now and no word back',
 'even my brother is not like to speak with me',
 'a per your request your callertune ha been activated',
 'congratulation you have won a walmart gift card reply claim',
 'are we still meeting for lunch today',
 'urgent your mobile number ha won cash prize',
 'can you pick up some milk on your way home',
 'you have been selected for a free vacation call now',
 'i ll call you later when i reach home',
 'exclusive offer buy get free limited time only',
 'don t forget to bring your notebook tomorrow',
 'win a brand new iphone text apple to',
 'thanks for helping me with the assignment',
 'your loan ha been approved contact u immediately',
 'i m stuck in traffic will be there in min',
 'you are our lucky customer receive cash reward now',
 'let s watch a movie this weekend',
 'get free ringtone by texting music to',
 'please send me the note from today s class',
 'claim your free coupon worth',
 'i reached the station safely',
 'limited offer lowest insurance rate guaranteed',
 'what s your plan for tonight',
 'winner you have won ticket to the concert',
 'happy birthday have a wonderful day',
 'earn per week from home join now',
 'can we reschedule the meeting to tomorrow',
 'final reminder your prize is waiting',
 'i am studying in the library',
 'free access to premium content click now',
 'did you complete the project report',
 'congratulation you ve been chosen for a cash bonus',
 'please call me when you get free',
 'get a free netflix subscription limited offer',
 'i will reach by pm',
 'you won a luxury holiday package call today',
 'have you eaten your dinner',
 'claim your cashback reward instantly',
 'the exam schedule ha been announced',
 'lowest loan rate available apply now',
 'i am waiting outside your house',
 'win guaranteed gift by participating today',
 'let s discus the presentation tomorrow',
 'get free mobile recharge worth',
 'the weather is very nice today',
 'you have won a shopping voucher',
 'can you send me the document',
 'special promotion buy now and save',
 'i will be late due to rain',
 'free entry into our lucky draw',
 'don t worry everything will be fine',
 'your account qualifies for a free upgrade',
 'meet me near the college gate',
 'exclusive deal just for you act now',
 'i have submitted the assignment',
 'win cash prize every day register now',
 'where are you right now',
 'get free movie ticket instantly',
 'the train ha arrived on platform',
 'you are selected for a free gift hamper',
 'please bring your id card tomorrow',
 'earn money online without investment',
 'i am attending the workshop',
 'limited stock available order today',
 'let s go for a walk in the evening',
 'congratulation you have won a free smartphone',
 'i completed the lab work',
 'claim your reward before midnight',
 'the meeting start at am',
 'you have received a bonus payment',
 'can you help me with this question',
 'special offer free shipping on all product',
 'i am at the bus stop',
 'you are eligible for a free credit card',
 'let s prepare together for the exam',
 'win a free laptop by entering our contest',
 'i will send the file tonight',
 'urgent verify your bank account detail now',
 'have a safe journey',
 'get free internet data pack',
 'the class ha been postponed',
 'you have won a mystery gift',
 'please check your email',
 'exclusive membership offer available now',
 'i am feeling better today',
 'claim your free travel voucher',
 'let s have tea after class',
 'your number ha been selected for a prize',
 'thank you for your support',
 'free recharge available reply yes',
 'i reached home safely',
 'congratulation you are our lucky winner',
 'see you tomorrow in college',
 'last chance to claim your reward',
 'can you share the lecture slide',
 'you have won cash call now',
 'good night and sweet dream',
 'free gift waiting for you text gift to']

In [50]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [51]:
words=[]
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

In [52]:
words

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'great',
  'world',
  'la'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'in',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'ticket',
  'text',
  'win',
  'to',
  'now'],
 ['dun', 'say', 'so', 'early', 'hor', 'already', 'then', 'say'],
 ['nah',
  'don',
  'think',
  'he',
  'go',
  'to',
  'usf',
  'he',
  'life',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darling',
  'it',
  'been',
  'week',
  'now',
  'and',
  'no',
  'word',
  'back'],
 ['even', 'my', 'brother', 'is', 'not', 'like', 'to', 'speak', 'with', 'me'],
 ['per', 'your', 'request', 'your', 'callertune', 'ha', 'been', 'activated'],
 ['congratulation',
  'you',
  'have',
  'won',
  'walmart',
  'gift',
  'card',
  'reply',
  'claim'],
 ['are', 'we', 'still', 'meeting', 'for', 'lunch', 'today'],
 ['urgent', 'your', 'mobile', 'number', 'ha', 'won', 'cash', 'prize'],
 ['can', 'you', 'pick', 'up', 'some', 'milk', 'on', 'your', 'way', 'home'],
 ['you', 'have', 'been', 'selected', 'for', 'free', 'vacation', 'call', 'now'],
 ['ll', 'call', 'you', 'later', 'when', 'reach', 'home'],
 ['exclusive', 'offer', 'buy', 'get', 'free', 'limited', 'time', 'only'],
 ['don', 'forget', 'to', 'bring', 'your', 'notebook', 'tomorrow'],
 ['win', 'brand', 'new', 'iphone', 'text', 'apple', 'to'],
 ['thanks', 'for', 'helping', 'me', 'with', 'the', 'assignment'],
 ['your', 'loan', 'ha', 'been', 'approved', 'contact', 'immediately'],
 ['stuck', 'in', 'traffic', 'will', 'be', 'there', 'in', 'min'],
 ['you',
  'are',
  'our',
  'lucky',
  'customer',
  'receive',
  'cash',
  'reward',
  'now'],
 ['let', 'watch', 'movie', 'this', 'weekend'],
 ['get', 'free', 'ringtone', 'by', 'texting', 'music', 'to'],
 ['please', 'send', 'me', 'the', 'note', 'from', 'today', 'class'],
 ['claim', 'your', 'free', 'coupon', 'worth'],
 ['reached', 'the', 'station', 'safely'],
 ['limited', 'offer', 'lowest', 'insurance', 'rate', 'guaranteed'],
 ['what', 'your', 'plan', 'for', 'tonight'],
 ['winner', 'you', 'have', 'won', 'ticket', 'to', 'the', 'concert'],
 ['happy', 'birthday', 'have', 'wonderful', 'day'],
 ['earn', 'per', 'week', 'from', 'home', 'join', 'now'],
 ['can', 'we', 'reschedule', 'the', 'meeting', 'to', 'tomorrow'],
 ['final', 'reminder', 'your', 'prize', 'is', 'waiting'],
 ['am', 'studying', 'in', 'the', 'library'],
 ['free', 'access', 'to', 'premium', 'content', 'click', 'now'],
 ['did', 'you', 'complete', 'the', 'project', 'report'],
 ['congratulation', 'you', 've', 'been', 'chosen', 'for', 'cash', 'bonus'],
 ['please', 'call', 'me', 'when', 'you', 'get', 'free'],
 ['get', 'free', 'netflix', 'subscription', 'limited', 'offer'],
 ['will', 'reach', 'by', 'pm'],
 ['you', 'won', 'luxury', 'holiday', 'package', 'call', 'today'],
 ['have', 'you', 'eaten', 'your', 'dinner'],
 ['claim', 'your', 'cashback', 'reward', 'instantly'],
 ['the', 'exam', 'schedule', 'ha', 'been', 'announced'],
 ['lowest', 'loan', 'rate', 'available', 'apply', 'now'],
 ['am', 'waiting', 'outside', 'your', 'house'],
 ['win', 'guaranteed', 'gift', 'by', 'participating', 'today'],
 ['let', 'discus', 'the', 'presentation', 'tomorrow'],
 ['get', 'free', 'mobile', 'recharge', 'worth'],
 ['the', 'weather', 'is', 'very', 'nice', 'today'],
 ['you', 'have', 'won', 'shopping', 'voucher'],
 ['can', 'you', 'send', 'me', 'the', 'document'],
 ['special', 'promotion', 'buy', 'now', 'and', 'save'],
 ['will', 'be', 'late', 'due', 'to', 'rain'],
 ['free', 'entry', 'into', 'our', 'lucky', 'draw'],
 ['don', 'worry', 'everything', 'will', 'be', 'fine'],
 ['your', 'account', 'qualifies', 'for', 'free', 'upgrade'],
 ['meet', 'me', 'near', 'the', 'college', 'gate'],
 ['exclusive', 'deal', 'just', 'for', 'you', 'act', 'now'],
 ['have', 'submitted', 'the', 'assignment'],
 ['win', 'cash', 'prize', 'every', 'day', 'register', 'now'],
 ['where', 'are', 'you', 'right', 'now'],
 ['get', 'free', 'movie', 'ticket', 'instantly'],
 ['the', 'train', 'ha', 'arrived', 'on', 'platform'],
 ['you', 'are', 'selected', 'for', 'free', 'gift', 'hamper'],
 ['please', 'bring', 'your', 'id', 'card', 'tomorrow'],
 ['earn', 'money', 'online', 'without', 'investment'],
 ['am', 'attending', 'the', 'workshop'],
 ['limited', 'stock', 'available', 'order', 'today'],
 ['let', 'go', 'for', 'walk', 'in', 'the', 'evening'],
 ['congratulation', 'you', 'have', 'won', 'free', 'smartphone'],
 ['completed', 'the', 'lab', 'work'],
 ['claim', 'your', 'reward', 'before', 'midnight'],
 ['the', 'meeting', 'start', 'at', 'am'],
 ['you', 'have', 'received', 'bonus', 'payment'],
 ['can', 'you', 'help', 'me', 'with', 'this', 'question'],
 ['special', 'offer', 'free', 'shipping', 'on', 'all', 'product'],
 ['am', 'at', 'the', 'bus', 'stop'],
 ['you', 'are', 'eligible', 'for', 'free', 'credit', 'card'],
 ['let', 'prepare', 'together', 'for', 'the', 'exam'],
 ['win', 'free', 'laptop', 'by', 'entering', 'our', 'contest'],
 ['will', 'send', 'the', 'file', 'tonight'],
 ['urgent', 'verify', 'your', 'bank', 'account', 'detail', 'now'],
 ['have', 'safe', 'journey'],
 ['get', 'free', 'internet', 'data', 'pack'],
 ['the', 'class', 'ha', 'been', 'postponed'],
 ['you', 'have', 'won', 'mystery', 'gift'],
 ['please', 'check', 'your', 'email'],
 ['exclusive', 'membership', 'offer', 'available', 'now'],
 ['am', 'feeling', 'better', 'today'],
 ['claim', 'your', 'free', 'travel', 'voucher'],
 ['let', 'have', 'tea', 'after', 'class'],
 ['your', 'number', 'ha', 'been', 'selected', 'for', 'prize'],
 ['thank', 'you', 'for', 'your', 'support'],
 ['free', 'recharge', 'available', 'reply', 'yes'],
 ['reached', 'home', 'safely'],
 ['congratulation', 'you', 'are', 'our', 'lucky', 'winner'],
 ['see', 'you', 'tomorrow', 'in', 'college'],
 ['last', 'chance', 'to', 'claim', 'your', 'reward'],
 ['can', 'you', 'share', 'the', 'lecture', 'slide'],
 ['you', 'have', 'won', 'cash', 'call', 'now'],
 ['good', 'night', 'and', 'sweet', 'dream'],
 ['free', 'gift', 'waiting', 'for', 'you', 'text', 'gift', 'to']]

In [53]:
import gensim

In [54]:
## lets train word2vec from scratch
model=gensim.models.Word2Vec(words)

In [55]:
## to get all the vocabulary
model.wv.index_to_key

['you',
 'the',
 'your',
 'free',
 'for',
 'now',
 'have',
 'to',
 'won',
 'been',
 'get',
 'today',
 'ha',
 'me',
 'in',
 'am',
 'are',
 'claim',
 'gift',
 'win',
 'let',
 'will',
 'tomorrow',
 'offer',
 'call',
 'can',
 'cash',
 'available']

In [56]:
model.corpus_count

103

In [57]:
model.epochs

5

In [58]:
model.wv.similar_by_word('won')

[('available', 0.2852645516395569),
 ('your', 0.1994498372077942),
 ('win', 0.09671062231063843),
 ('free', 0.07499343901872635),
 ('now', 0.060777872800827026),
 ('been', 0.04491269215941429),
 ('today', 0.038229793310165405),
 ('cash', 0.03529460355639458),
 ('the', 0.033792588859796524),
 ('you', 0.027570612728595734)]

In [59]:
model.wv.similar_by_word('claim')

[('in', 0.24679359793663025),
 ('gift', 0.11968827992677689),
 ('to', 0.1196475476026535),
 ('me', 0.11728177219629288),
 ('get', 0.09611615538597107),
 ('call', 0.08813843876123428),
 ('the', 0.0854528620839119),
 ('cash', 0.07603998482227325),
 ('now', 0.0728444829583168),
 ('today', 0.06038469821214676)]

In [60]:
model.wv['claim'].shape

(100,)

In [61]:
words[0]

['go',
 'until',
 'jurong',
 'point',
 'crazy',
 'available',
 'only',
 'in',
 'bugis',
 'great',
 'world',
 'la']

In [62]:
import numpy as np

In [63]:
def avg_word2vec(doc):
    # remove out-of-vocabulary words
    sent = [word for word in doc if word in model.wv.index_to_key]
    
    if len(sent) == 0:
        # handle empty case gracefully
        return np.zeros(model.vector_size)
    
    return np.mean([model.wv[word] for word in sent], axis=0)

In [35]:
!pip install tqdm

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: tqdm in c:\users\sonup\appdata\roaming\python\python311\site-packages (4.68.3)
Requirement already satisfied: colorama in c:\users\sonup\appdata\roaming\python\python311\site-packages (from tqdm) (0.4.6)

[notice] A new release of pip is available: 23.2.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [36]:
from tqdm import tqdm

In [37]:
## apply for entire sentences

x=[]
for i in tqdm(range(len(words))):
    x.append(avg_word2vec(words[i]))

100%|██████████| 103/103 [00:00<00:00, 11444.36it/s]

In [38]:
x

[array([ 4.9058748e-03,  7.4276323e-03, -4.9026095e-04, -2.5762797e-03,
         8.4345844e-03, -1.6555474e-03,  6.0211276e-03, -1.1745242e-03,
         8.1317378e-03, -2.3035975e-03,  7.1459198e-03, -9.5994147e-03,
        -3.6690431e-03, -2.9472797e-03, -5.6876712e-03,  3.3675181e-04,
         7.7664861e-03, -5.0751660e-03, -7.2944991e-04,  2.2445023e-03,
         4.3193786e-04,  7.2049974e-03,  3.2995766e-04,  3.8850086e-04,
        -5.1207566e-03, -3.3002696e-04, -3.7483335e-03, -1.6133809e-03,
         1.3670819e-03, -3.5632788e-03, -5.1721279e-04, -4.9495874e-03,
        -3.0919111e-03, -5.9513114e-03, -6.0450677e-03, -8.6689517e-03,
         4.0581552e-03,  8.4339967e-03,  3.8694122e-03,  1.0452631e-03,
        -9.0916641e-05, -1.5222627e-03, -1.3253617e-03, -6.5038144e-04,
        -4.3336931e-04,  5.1391781e-03, -6.1555412e-03, -4.6909205e-04,
         1.5812786e-03,  4.7753882e-03,  6.4239150e-04, -2.3371857e-03,
         4.9051894e-03, -7.1727578e-03,  8.5053523e-04, -2.6326622e-03,
         9.2489980e-03,  3.2687534e-03, -8.2871906e-04,  5.2999668e-03,
        -7.3624142e-03, -7.3425332e-03,  3.4332988e-03,  1.9789296e-03,
        -1.1740392e-04,  2.0469797e-03, -5.9318459e-03, -1.5416633e-03,
        -4.2541168e-04, -3.0849329e-03, -1.5078476e-03, -1.5468427e-03,
         6.4388169e-03, -4.5000650e-03, -3.4374960e-03, -8.2975477e-03,
         1.9594422e-04, -1.4286422e-03,  2.4884811e-04, -2.8601557e-03,
        -6.3811848e-03, -2.5587686e-04,  4.6584154e-03, -3.4978457e-03,
         6.6358028e-03, -2.9428559e-03,  1.4637348e-03,  2.1207801e-03,
         2.8838704e-03, -3.0282605e-03,  4.3186378e-03,  1.5957864e-03,
         4.0606987e-03, -1.5072143e-03,  2.5849557e-03, -3.3201789e-04,
         2.6404455e-03,  6.3524786e-03, -7.0922761e-03,  2.6890959e-03],
       dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([ 2.61190347e-03,  3.23470635e-03,  3.09540494e-03,  1.20419450e-03,
        -3.31544480e-03,  6.39848527e-04,  5.70791122e-03, -1.65717080e-04,
         1.79047769e-04, -6.74615894e-03,  2.04649195e-03, -2.81365268e-04,
         2.14757537e-03, -4.11197124e-03,  7.05567596e-04,  6.27463800e-04,
         5.50226076e-03, -3.68794054e-03, -4.56589414e-03, -3.48659442e-03,
        -5.58941159e-04,  3.76368710e-03,  6.28644717e-04, -1.43199705e-03,
        -8.06741323e-03,  3.86028993e-03, -2.87554081e-04, -1.98812550e-03,
         8.68397183e-04,  5.41668152e-03, -3.10954335e-03, -2.84625776e-03,
        -1.08650711e-03, -4.48282808e-03, -4.00627544e-03,  3.44709633e-03,
        -1.63392426e-04, -8.21235648e-04, -3.58532346e-03,  1.17849198e-03,
         6.07827725e-03,  1.66198611e-03,  1.82569341e-03,  3.13409395e-03,
         4.00931155e-03, -5.32262551e-04, -3.08876880e-03, -2.92880670e-03,
         3.18540819e-03,  8.80729523e-04, -3.69623187e-03, -2.28863815e-03,
         3.37553880e-04, -5.15684532e-03, -3.07322503e-03,  4.43122257e-03,
         1.69053033e-03,  2.73400103e-03,  2.34103785e-03,  4.53100685e-04,
         2.12893379e-03, -3.59869143e-03,  1.67917623e-03,  1.41859916e-03,
         2.42203963e-03,  4.27878927e-03, -5.00425277e-03,  2.63535115e-03,
        -3.66883934e-03, -5.91439009e-03,  2.86362658e-04, -3.08696704e-04,
         4.19774372e-03,  2.15051023e-05, -3.17948917e-03,  3.71610280e-04,
         3.19039938e-03,  1.72231707e-03, -6.04354660e-04, -2.29920330e-03,
        -4.29386133e-03, -1.48145817e-04, -1.05357794e-04, -9.75808420e-04,
         2.93723727e-03, -2.73626437e-03,  3.04253376e-03,  4.00525052e-03,
         1.07730913e-03, -4.70223557e-03,  1.57118961e-03,  6.30431692e-04,
        -5.34990570e-03,  4.41272836e-03, -1.08543252e-04, -3.15439375e-03,
        -2.32660072e-03, -3.37702164e-04,  1.92163640e-03,  1.02591119e-03],
       dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([ 8.1647141e-03, -4.4431617e-03,  8.9818845e-03,  8.2598859e-03,
        -4.4346820e-03,  2.9873688e-04,  4.2757308e-03, -3.9207637e-03,
        -5.5655167e-03, -6.5167476e-03, -6.7163794e-04, -2.9818623e-04,
         4.4646361e-03, -2.4713124e-03, -1.7131609e-04,  2.4646870e-03,
         4.8705442e-03, -3.1037074e-05, -6.3360054e-03, -9.2682615e-03,
         2.8427370e-05,  6.6629043e-03,  1.4646931e-03, -8.9633157e-03,
        -7.9347584e-03,  6.5523828e-03, -3.7900507e-03,  6.2625185e-03,
        -6.6838386e-03,  8.4776497e-03, -6.5122638e-03,  3.2927264e-03,
        -1.0585317e-03, -6.7889155e-03, -3.2891741e-03, -1.1570902e-03,
        -5.4681157e-03, -1.2119227e-03, -7.5668385e-03,  2.6513131e-03,
         9.0755094e-03, -2.3781529e-03, -9.8074868e-04,  3.5121718e-03,
         8.6684804e-03, -5.9228437e-03, -6.8896036e-03, -2.9319413e-03,
         9.1502946e-03,  8.6631993e-04, -8.6734854e-03, -1.4434033e-03,
         9.4776722e-03, -7.5476533e-03, -5.3573917e-03,  9.3129845e-03,
        -8.9787403e-03,  3.8207460e-03,  6.6671584e-04,  6.6588600e-03,
         8.3111618e-03, -2.8506003e-03, -3.9857137e-03,  8.8999551e-03,
         2.0885726e-03,  6.2497663e-03, -9.4479360e-03,  9.5900148e-03,
        -1.3516539e-03, -6.0515925e-03,  2.9921916e-03, -4.5165393e-04,
         4.7046407e-03, -2.2860661e-03, -4.1375542e-03,  2.2791033e-03,
         8.3560161e-03, -4.9928539e-03,  2.6737063e-03, -7.9900296e-03,
        -6.7763394e-03, -4.6946129e-04, -8.7662777e-03,  2.7917128e-03,
         1.5970160e-03, -2.3237665e-03,  5.0074416e-03,  9.7503662e-03,
         8.4589291e-03, -1.8789083e-03,  2.0551728e-03, -4.0015616e-03,
        -8.2399948e-03,  6.2805037e-03, -1.9401291e-03, -6.7253824e-04,
        -1.7721449e-03, -4.5352341e-03,  4.0675709e-03, -4.2673512e-03],
       dtype=float32),
 array([-6.9577447e-03, -2.2728518e-03, -4.3261931e-03, -4.9630133e-04,
        -5.7119858e-03, -4.1479813e-03,  1.5668292e-04,  4.4503389e-03,
        -4.7198082e-03, -5.3327698e-03, -1.7044336e-03, -2.5393874e-03,
        -4.4269054e-03, -4.2587053e-03, -2.8641075e-03,  8.4151514e-05,
        -1.0575536e-03, -7.8044934e-03,  1.9413831e-03, -4.2758211e-03,
        -4.0813116e-03,  1.8423868e-03,  1.5426446e-03,  2.8013238e-03,
         4.3990742e-04, -3.9487989e-03, -2.2611083e-03, -1.5771808e-04,
        -3.5712041e-04,  9.1285422e-04,  7.1783797e-03, -2.2375290e-03,
        -9.5200725e-05,  5.4106116e-04, -4.1974443e-03,  7.2709518e-03,
         4.0179468e-03,  4.6291593e-03,  3.3723693e-03,  6.0113193e-04,
         7.0312880e-03, -6.5026758e-04, -5.2520400e-03, -3.4077312e-03,
        -5.7724776e-04, -3.5962556e-04, -1.9444939e-03,  6.7740148e-03,
         1.7657895e-03,  3.0707046e-03,  2.6535376e-03, -1.2252899e-04,
         3.2407520e-03,  8.3062677e-03, -2.9370422e-03, -2.7848519e-03,
         2.9828635e-03, -5.0905012e-03, -1.0488846e-03, -4.2963931e-03,
         2.8095543e-03,  3.5794398e-03,  9.2533138e-03, -4.8739216e-03,
        -7.0769177e-04, -1.0116814e-03, -2.0592390e-03, -3.6049224e-03,
        -3.0606047e-03, -6.7865727e-03,  2.4562173e-03,  5.8957553e-03,
         1.9706071e-03, -1.9286091e-03,  3.9289551e-04,  8.1520341e-04,
        -3.3995372e-03, -1.7364440e-04,  3.6868851e-03,  2.2311849e-03,
         5.4681930e-03, -4.7483412e-03,  1.9319847e-03, -9.2935120e-04,
         2.9744153e-04, -7.2830068e-03, -6.4567300e-03,  5.2810959e-03,
         2.3075573e-03,  4.2308876e-03,  7.4545853e-05,  8.7718824e-03,
        -2.0718365e-03,  2.2364482e-03,  9.8400153e-03, -1.0944766e-03,
        -5.3129308e-03, -1.4531836e-03,  6.1887698e-03, -1.5859664e-03],
       dtype=float32),
 array([-6.6428864e-04,  2.5534418e-03,  6.0415594e-04,  2.8123609e-03,
        -4.6691885e-03, -2.3388788e-03, -1.8680580e-03, -5.8428827e-03,
        -5.0709341e-03, -3.9024856e-03, -2.8914362e-03,  2.9166813e-03,
        -2.5274309e-03, -3.8849046e-03,  4.6318076e-03,  4.7273794e-03,
         6.2756832e-03,  2.1019380e-03, -2.9137714e-03, -7.6386621e-03,
         3.0299968e-03,  4.6484079e-03,  4.5861928e-03, -1.2901195e-03,
         3.0240044e-06,  7.6031350e-03, -6.8486980e-03, -2.4359021e-04,
        -2.6764076e-03,  7.4613239e-03,  4.3687504e-04,  4.4037560e-03,
         3.3017830e-03, -5.9633981e-03,  1.6452797e-03, -2.6288992e-03,
        -7.2626201e-03,  3.9700079e-03, -3.1177320e-03, -6.2821782e-05,
         3.3034931e-03, -3.3070408e-03,  1.9134132e-03,  3.9625932e-03,
         3.0113396e-03, -6.6351518e-03, -5.2364562e-03, -1.6339992e-03,
         7.6353503e-03, -9.8097580e-04, -4.4014710e-03, -2.8466547e-04,
         1.1963283e-03, -2.7402057e-03, -3.3953143e-03,  6.0613416e-03,
        -2.0708572e-03,  1.2286797e-03, -1.0593025e-03,  7.1996339e-03,
         6.6840909e-03,  1.9344456e-03,  2.7122418e-04,  8.7867053e-03,
         4.7772666e-03,  2.5937043e-03, -3.5068626e-04,  7.1064020e-03,
         2.0416067e-03, -3.7206428e-03,  4.8270042e-04, -2.4327389e-03,
        -1.9001353e-03,  3.7627877e-04,  2.3793476e-03,  5.5991523e-03,
         3.2141709e-03,  5.5021862e-04,  3.2286164e-03, -6.1493572e-03,
        -2.3699929e-03, -2.9567597e-03, -2.8376887e-04,  4.1155135e-03,
         2.3938257e-03,  8.8432420e-04,  6.8328679e-03,  8.5155377e-03,
         3.8156663e-03, -4.4763791e-03,  5.2274475e-03,  1.6186496e-03,
        -3.2519461e-03,  2.4727578e-03, -3.9075334e-03, -2.5998722e-03,
         3.4335358e-03, -3.8407512e-03, -1.1309527e-03,  2.8011256e-03],
       dtype=float32),
 array([-1.7291438e-03, -1.4484493e-03, -2.9845778e-03, -9.2889625e-04,
         4.4617872e-03,  3.3064620e-03, -3.2166764e-03,  4.8703896e-03,
        -2.4170147e-03,  7.9002709e-04, -3.4177324e-03, -3.9657806e-03,
         2.2838905e-03, -4.8968446e-05,  1.5955279e-03, -2.9923546e-03,
         3.7601534e-03,  3.2254972e-03, -1.0714582e-03, -4.9363300e-03,
        -4.4459668e-03, -1.0129841e-03, -3.0557951e-03, -2.7640290e-03,
         6.0451198e-03, -1.6727921e-03,  2.3967773e-04,  7.0522949e-03,
        -4.2963242e-03,  2.9766257e-03,  2.9767537e-03, -2.1905219e-03,
        -2.3554270e-03,  1.0841379e-03, -7.7041443e-03, -1.7836521e-03,
        -1.5042694e-03,  7.0105901e-04,  1.6160161e-03,  7.8794023e-04,
        -2.1252851e-03,  4.1639893e-03, -1.8731989e-03,  1.9158964e-03,
        -3.3255623e-04,  4.1560153e-04,  2.1288234e-03, -1.2777511e-03,
        -2.7269924e-03,  2.7286403e-03,  3.0241231e-03, -1.0035043e-03,
        -3.6465044e-03, -3.3865958e-03, -3.2220089e-03, -6.0515413e-03,
        -2.7680895e-03, -2.2451112e-03,  1.4773884e-04, -3.9260779e-04,
        -9.7438233e-04, -1.3198545e-03,  8.4938277e-03,  8.6225686e-04,
        -5.9768450e-03,  3.7012810e-03,  4.9763313e-03,  8.0432277e-05,
        -5.4441919e-03,  2.2586240e-03,  4.2015575e-03,  5.5764169e-03,
         2.1366426e-03, -2.8426955e-03, -1.2876241e-03,  2.4864133e-03,
         6.5889447e-03, -1.0551556e-03, -1.6501792e-03,  2.2593728e-04,
        -6.5171608e-04, -3.4640224e-03, -4.6502417e-03,  4.2941528e-03,
        -3.7127818e-04, -4.4611180e-03, -2.3753254e-03, -4.3805805e-03,
         4.5247651e-03,  1.8487026e-03, -3.8290666e-03,  4.3589883e-03,
         7.2172089e-03, -2.0966630e-03,  7.2753029e-03,  9.9082792e-04,
         2.8618730e-03,  3.1983894e-03,  8.1609292e-03, -6.7521818e-04],
       dtype=float32),
 array([ 1.9035405e-03,  3.9343414e-04,  9.2457852e-04,  3.0172025e-03,
         2.2549902e-03, -2.8967094e-03,  6.8407105e-03,  3.3481538e-03,
        -5.2028052e-03, -2.3854703e-03,  1.5204179e-03, -3.1048281e-03,
         3.1235598e-03,  3.8799229e-03,  2.7888429e-03, -2.2179175e-03,
         2.0679226e-03,  2.5935390e-03,  4.9281790e-04, -4.9833879e-03,
         4.5861844e-03, -9.2246570e-05,  3.1471029e-03, -3.1841241e-03,
         2.8171216e-03, -8.8214257e-04, -3.4540244e-03, -1.6681526e-03,
         5.6218507e-04, -3.6022055e-03,  2.5891352e-03,  1.0472573e-03,
         6.3379837e-04,  3.6597688e-04, -6.5196201e-04,  1.8791009e-03,
        -1.5210793e-03,  1.1290505e-03,  2.0456719e-03, -7.1145333e-03,
         3.3983999e-04, -2.3830358e-03,  2.8341054e-03, -1.9169292e-04,
        -1.3150959e-04,  9.6360513e-04, -5.0056777e-03,  1.4202650e-04,
         1.5156337e-03,  3.4684115e-04, -1.2557458e-03, -3.0111242e-04,
        -1.3939406e-03, -1.1986207e-03,  3.5498911e-03, -1.3181119e-03,
         1.1541263e-03, -2.0750628e-03,  8.7378157e-04, -1.3233893e-04,
        -2.5904682e-03, -9.2858088e-04,  2.7440358e-03,  3.7429979e-04,
        -2.7918173e-03,  3.7950657e-03, -8.5503981e-04,  3.8397647e-03,
        -2.6926356e-03, -7.1543606e-04,  7.0882862e-04,  9.6039183e-04,
         2.4310406e-03,  3.0408972e-03,  4.1106362e-03, -1.9139521e-03,
         2.0272615e-03,  2.0478007e-03, -3.4570280e-03, -5.7184009e-04,
        -1.3991066e-03, -4.8949255e-04,  1.6160170e-03,  3.0870026e-03,
         3.2451819e-03,  2.7347059e-04,  5.4910015e-03, -2.4816203e-03,
        -7.9544133e-04,  8.3426927e-04,  2.0979184e-03,  2.1774853e-04,
         2.7964399e-03,  7.5560331e-04,  5.7594320e-03,  4.9201353e-03,
         7.2148035e-04, -2.0639263e-03,  2.5203465e-03, -6.1635488e-05],
       dtype=float32),
 array([ 1.3016289e-03, -1.3484154e-04, -4.4195974e-04,  7.8035449e-04,
         3.8166158e-03,  3.7197428e-04, -1.0993184e-03,  5.4643978e-03,
        -2.4276960e-03,  1.0803941e-03, -2.0049892e-03, -3.6984068e-04,
        -5.9563816e-03,  2.6207657e-03, -2.6376564e-03, -3.1041494e-04,
        -5.1952316e-03, -3.6273772e-04, -1.2669386e-04, -7.5498843e-03,
         1.6610600e-03, -3.4086660e-03,  4.1034203e-03,  1.8267572e-03,
        -4.1841590e-03,  6.7151897e-04,  3.2460349e-04,  7.6439278e-04,
        -3.1011545e-03, -1.1119301e-04,  2.3427019e-03, -3.1695713e-03,
         1.0426062e-03, -5.5770776e-03,  3.8168896e-03, -2.2460816e-04,
         9.1156224e-04,  8.5732849e-05, -5.7410523e-03, -4.5822212e-03,
        -2.4325552e-03, -5.1791361e-03, -4.9146027e-03,  7.5353286e-03,
         3.8219697e-03, -2.3825355e-03,  1.6449001e-03, -1.8068039e-03,
         3.4968152e-03,  1.8107472e-03,  4.8876595e-04, -2.7975645e-03,
         5.7744142e-03,  1.1712991e-03, -2.1263633e-03, -1.5151765e-03,
        -4.8256055e-03, -4.4335499e-03, -3.2735039e-03, -3.0262175e-03,
         3.7582342e-03, -2.6397698e-04,  1.8845868e-03,  1.0961145e-03,
        -3.1697934e-03,  3.5096221e-03,  2.8127905e-03,  8.4059602e-03,
        -2.3199851e-03,  5.6165420e-03, -6.5233227e-04,  8.0178985e-03,
         1.8757519e-04,  2.1276872e-03,  1.9924769e-03,  1.4016674e-03,
         1.2225099e-04,  3.4493806e-03,  4.5455666e-03, -6.1293668e-03,
        -3.1390076e-03, -2.3701033e-03, -4.5050331e-03, -4.2644865e-03,
        -2.5542451e-03, -2.6186004e-03, -1.7264070e-03, -3.1096544e-03,
        -1.8825332e-03, -8.8143552e-04,  4.9997377e-03, -1.0383318e-03,
         1.5767490e-03,  2.2196034e-03,  1.3951488e-03, -2.1448755e-03,
        -3.6507258e-03, -2.6970310e-04, -3.9575882e-03,  1.6354406e-03],
       dtype=float32),
 array([-4.6001310e-03,  1.0706029e-03, -3.0681491e-04,  1.5245103e-03,
         6.2351432e-03,  5.2267988e-03,  3.2841447e-03,  1.6488093e-03,
        -3.6541740e-03,  3.5123443e-03, -2.9655700e-03, -1.9359845e-03,
         4.1583572e-03, -1.6916526e-03,  9.3889749e-04, -3.7593488e-03,
         1.4689359e-03,  9.9815044e-04, -2.0022003e-03, -4.7017513e-03,
        -4.2873202e-04,  7.5568858e-04,  3.8642238e-03, -3.1775064e-03,
         4.7567952e-04, -9.9171721e-04, -1.6025926e-03,  2.2951006e-03,
        -1.9227592e-03,  3.4294929e-03,  1.8282693e-03, -1.9190797e-03,
         5.4989406e-04,  3.8772384e-03, -4.0736063e-03,  2.8339797e-04,
        -4.7482336e-03,  1.4019179e-03,  1.6451022e-03, -2.2515436e-03,
        -7.4052473e-04,  2.3998534e-03, -1.4660303e-03,  1.0383863e-03,
        -1.6102341e-03, -2.6617281e-03,  4.2991675e-03, -2.7140484e-03,
        -1.7625515e-03,  6.6164524e-05,  2.6638131e-03, -1.4996722e-03,
        -1.6454890e-03, -4.2187427e-03, -1.5769498e-03, -1.9125248e-03,
        -7.3681871e-04, -1.2055491e-03, -1.4880137e-04, -3.4584501e-03,
        -2.9659977e-03, -4.8971153e-03,  6.1553596e-03, -5.6817790e-04,
        -7.3977942e-03,  2.6504388e-03,  4.6505174e-03,  2.0568313e-03,
        -8.2668914e-03,  3.3671469e-03,  1.5749718e-04,  1.8149328e-03,
         3.3112529e-03,  7.5968984e-04, -3.5795451e-03, -1.9285125e-03,
         3.7605104e-03, -2.1026265e-03, -5.7165986e-03,  1.3581389e-03,
        -1.9419445e-03, -6.8664318e-04, -8.5611711e-04,  4.5920769e-03,
         4.1400071e-04, -2.7154754e-03, -2.1979178e-04, -2.2907092e-03,
         4.2984466e-04,  1.7682861e-03,  3.8704579e-04, -5.0182478e-04,
         4.1925590e-03, -5.3663817e-03,  3.6659152e-03,  1.4089709e-03,
         5.2357083e-03,  4.0766052e-03,  6.6363746e-03, -5.4453051e-04],
       dtype=float32),
 array([ 3.06412554e-03,  3.53955384e-03, -1.48396633e-04,  1.41619204e-03,
        -6.97404437e-04,  2.05248594e-04, -1.19311002e-03,  5.81200467e-03,
        -3.67548014e-03,  2.06005317e-03, -1.50419027e-03,  1.26904261e-03,
         1.74993742e-03,  2.42073252e-03, -2.15908489e-03, -1.27641729e-03,
         4.94069047e-03,  6.09304337e-03, -7.73280347e-03, -7.52251083e-03,
        -1.74604042e-03, -1.27052888e-04, -1.76810136e-03, -5.33280335e-03,
         4.12652129e-03, -2.37016589e-03, -6.75499439e-04,  2.42639589e-03,
        -4.48993547e-03,  2.27627694e-03, -8.56945626e-05, -2.99422839e-03,
        -1.77725533e-03, -5.52701764e-03, -3.88709363e-03,  1.32698298e-03,
         4.37984290e-03, -1.37707312e-03,  8.77399696e-04, -5.09727886e-03,
        -5.52171888e-03,  6.88145403e-04, -1.29006745e-03,  2.50227749e-05,
        -2.56248750e-04, -1.74984464e-03, -2.49164202e-03, -9.81360208e-05,
        -3.34822427e-04,  1.38779730e-03, -3.03430762e-03, -4.68340615e-04,
        -6.45552622e-03, -2.73753027e-03,  3.53874319e-04, -4.81845206e-03,
        -1.65629305e-03, -4.91950801e-03, -6.36783661e-03,  1.64129946e-03,
         2.87877652e-03, -2.12472491e-03,  2.48076278e-03, -3.82854952e-04,
        -1.00798905e-04,  5.85808605e-03,  5.40694268e-03,  4.75091860e-04,
        -5.86008094e-03,  4.43690311e-04,  6.77879900e-04,  1.87584583e-03,
        -1.65868911e-03, -3.40285501e-03,  8.78533057e-04,  2.01268704e-03,
         2.76906672e-03,  2.66542309e-03, -1.51447486e-03, -1.39291224e-03,
         2.52325158e-03,  6.61030121e-04, -1.22052978e-03,  3.49885249e-03,
        -3.20232497e-03, -6.68840483e-04,  1.97128090e-03, -7.51956366e-04,
         6.78469427e-04,  3.25699989e-03, -2.85673514e-03,  1.23522175e-03,
         6.93688774e-03, -2.58935173e-03,  5.48397563e-03,  3.86503671e-04,
        -4.17771330e-03,  7.66240351e-04,  1.14069181e-03,  1.47960987e-03],
       dtype=float32),
 array([-3.8170654e-03,  6.8870722e-05, -1.2497066e-03, -2.2227889e-04,
        -3.1874313e-03, -3.1269214e-03,  3.7064489e-03,  4.6344483e-03,
        -2.9569704e-03, -3.5221216e-03,  2.0344069e-03,  1.0113992e-03,
        -2.8112563e-03,  6.4130605e-04, -2.3399605e-03, -5.8445882e-04,
         2.4570248e-03,  1.8827431e-04, -2.1832616e-03, -4.3643536e-03,
        -8.9923345e-04, -6.5515708e-04,  4.1148923e-03,  4.4834963e-03,
        -1.4596239e-03, -1.6543756e-03,  6.6314550e-04,  2.3527151e-04,
        -1.8846877e-03, -1.4782082e-03,  4.4256155e-03,  1.5116844e-03,
         6.3654326e-04, -1.2806632e-03,  2.1927763e-05,  1.5620989e-03,

In [64]:
len(x)

103

In [65]:
##independent features
x_new=np.array(x)

In [66]:
x_new.shape

(103, 100)

In [68]:
x

[array([ 4.9058748e-03,  7.4276323e-03, -4.9026095e-04, -2.5762797e-03,
         8.4345844e-03, -1.6555474e-03,  6.0211276e-03, -1.1745242e-03,
         8.1317378e-03, -2.3035975e-03,  7.1459198e-03, -9.5994147e-03,
        -3.6690431e-03, -2.9472797e-03, -5.6876712e-03,  3.3675181e-04,
         7.7664861e-03, -5.0751660e-03, -7.2944991e-04,  2.2445023e-03,
         4.3193786e-04,  7.2049974e-03,  3.2995766e-04,  3.8850086e-04,
        -5.1207566e-03, -3.3002696e-04, -3.7483335e-03, -1.6133809e-03,
         1.3670819e-03, -3.5632788e-03, -5.1721279e-04, -4.9495874e-03,
        -3.0919111e-03, -5.9513114e-03, -6.0450677e-03, -8.6689517e-03,
         4.0581552e-03,  8.4339967e-03,  3.8694122e-03,  1.0452631e-03,
        -9.0916641e-05, -1.5222627e-03, -1.3253617e-03, -6.5038144e-04,
        -4.3336931e-04,  5.1391781e-03, -6.1555412e-03, -4.6909205e-04,
         1.5812786e-03,  4.7753882e-03,  6.4239150e-04, -2.3371857e-03,
         4.9051894e-03, -7.1727578e-03,  8.5053523e-04, -2.6326622e-03,
         9.2489980e-03,  3.2687534e-03, -8.2871906e-04,  5.2999668e-03,
        -7.3624142e-03, -7.3425332e-03,  3.4332988e-03,  1.9789296e-03,
        -1.1740392e-04,  2.0469797e-03, -5.9318459e-03, -1.5416633e-03,
        -4.2541168e-04, -3.0849329e-03, -1.5078476e-03, -1.5468427e-03,
         6.4388169e-03, -4.5000650e-03, -3.4374960e-03, -8.2975477e-03,
         1.9594422e-04, -1.4286422e-03,  2.4884811e-04, -2.8601557e-03,
        -6.3811848e-03, -2.5587686e-04,  4.6584154e-03, -3.4978457e-03,
         6.6358028e-03, -2.9428559e-03,  1.4637348e-03,  2.1207801e-03,
         2.8838704e-03, -3.0282605e-03,  4.3186378e-03,  1.5957864e-03,
         4.0606987e-03, -1.5072143e-03,  2.5849557e-03, -3.3201789e-04,
         2.6404455e-03,  6.3524786e-03, -7.0922761e-03,  2.6890959e-03],
       dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([ 2.61190347e-03,  3.23470635e-03,  3.09540494e-03,  1.20419450e-03,
        -3.31544480e-03,  6.39848527e-04,  5.70791122e-03, -1.65717080e-04,
         1.79047769e-04, -6.74615894e-03,  2.04649195e-03, -2.81365268e-04,
         2.14757537e-03, -4.11197124e-03,  7.05567596e-04,  6.27463800e-04,
         5.50226076e-03, -3.68794054e-03, -4.56589414e-03, -3.48659442e-03,
        -5.58941159e-04,  3.76368710e-03,  6.28644717e-04, -1.43199705e-03,
        -8.06741323e-03,  3.86028993e-03, -2.87554081e-04, -1.98812550e-03,
         8.68397183e-04,  5.41668152e-03, -3.10954335e-03, -2.84625776e-03,
        -1.08650711e-03, -4.48282808e-03, -4.00627544e-03,  3.44709633e-03,
        -1.63392426e-04, -8.21235648e-04, -3.58532346e-03,  1.17849198e-03,
         6.07827725e-03,  1.66198611e-03,  1.82569341e-03,  3.13409395e-03,
         4.00931155e-03, -5.32262551e-04, -3.08876880e-03, -2.92880670e-03,
         3.18540819e-03,  8.80729523e-04, -3.69623187e-03, -2.28863815e-03,
         3.37553880e-04, -5.15684532e-03, -3.07322503e-03,  4.43122257e-03,
         1.69053033e-03,  2.73400103e-03,  2.34103785e-03,  4.53100685e-04,
         2.12893379e-03, -3.59869143e-03,  1.67917623e-03,  1.41859916e-03,
         2.42203963e-03,  4.27878927e-03, -5.00425277e-03,  2.63535115e-03,
        -3.66883934e-03, -5.91439009e-03,  2.86362658e-04, -3.08696704e-04,
         4.19774372e-03,  2.15051023e-05, -3.17948917e-03,  3.71610280e-04,
         3.19039938e-03,  1.72231707e-03, -6.04354660e-04, -2.29920330e-03,
        -4.29386133e-03, -1.48145817e-04, -1.05357794e-04, -9.75808420e-04,
         2.93723727e-03, -2.73626437e-03,  3.04253376e-03,  4.00525052e-03,
         1.07730913e-03, -4.70223557e-03,  1.57118961e-03,  6.30431692e-04,
        -5.34990570e-03,  4.41272836e-03, -1.08543252e-04, -3.15439375e-03,
        -2.32660072e-03, -3.37702164e-04,  1.92163640e-03,  1.02591119e-03],
       dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([ 8.1647141e-03, -4.4431617e-03,  8.9818845e-03,  8.2598859e-03,
        -4.4346820e-03,  2.9873688e-04,  4.2757308e-03, -3.9207637e-03,
        -5.5655167e-03, -6.5167476e-03, -6.7163794e-04, -2.9818623e-04,
         4.4646361e-03, -2.4713124e-03, -1.7131609e-04,  2.4646870e-03,
         4.8705442e-03, -3.1037074e-05, -6.3360054e-03, -9.2682615e-03,
         2.8427370e-05,  6.6629043e-03,  1.4646931e-03, -8.9633157e-03,
        -7.9347584e-03,  6.5523828e-03, -3.7900507e-03,  6.2625185e-03,
        -6.6838386e-03,  8.4776497e-03, -6.5122638e-03,  3.2927264e-03,
        -1.0585317e-03, -6.7889155e-03, -3.2891741e-03, -1.1570902e-03,
        -5.4681157e-03, -1.2119227e-03, -7.5668385e-03,  2.6513131e-03,
         9.0755094e-03, -2.3781529e-03, -9.8074868e-04,  3.5121718e-03,
         8.6684804e-03, -5.9228437e-03, -6.8896036e-03, -2.9319413e-03,
         9.1502946e-03,  8.6631993e-04, -8.6734854e-03, -1.4434033e-03,
         9.4776722e-03, -7.5476533e-03, -5.3573917e-03,  9.3129845e-03,
        -8.9787403e-03,  3.8207460e-03,  6.6671584e-04,  6.6588600e-03,
         8.3111618e-03, -2.8506003e-03, -3.9857137e-03,  8.8999551e-03,
         2.0885726e-03,  6.2497663e-03, -9.4479360e-03,  9.5900148e-03,
        -1.3516539e-03, -6.0515925e-03,  2.9921916e-03, -4.5165393e-04,
         4.7046407e-03, -2.2860661e-03, -4.1375542e-03,  2.2791033e-03,
         8.3560161e-03, -4.9928539e-03,  2.6737063e-03, -7.9900296e-03,
        -6.7763394e-03, -4.6946129e-04, -8.7662777e-03,  2.7917128e-03,
         1.5970160e-03, -2.3237665e-03,  5.0074416e-03,  9.7503662e-03,
         8.4589291e-03, -1.8789083e-03,  2.0551728e-03, -4.0015616e-03,
        -8.2399948e-03,  6.2805037e-03, -1.9401291e-03, -6.7253824e-04,
        -1.7721449e-03, -4.5352341e-03,  4.0675709e-03, -4.2673512e-03],
       dtype=float32),
 array([-6.9577447e-03, -2.2728518e-03, -4.3261931e-03, -4.9630133e-04,
        -5.7119858e-03, -4.1479813e-03,  1.5668292e-04,  4.4503389e-03,
        -4.7198082e-03, -5.3327698e-03, -1.7044336e-03, -2.5393874e-03,
        -4.4269054e-03, -4.2587053e-03, -2.8641075e-03,  8.4151514e-05,
        -1.0575536e-03, -7.8044934e-03,  1.9413831e-03, -4.2758211e-03,
        -4.0813116e-03,  1.8423868e-03,  1.5426446e-03,  2.8013238e-03,
         4.3990742e-04, -3.9487989e-03, -2.2611083e-03, -1.5771808e-04,
        -3.5712041e-04,  9.1285422e-04,  7.1783797e-03, -2.2375290e-03,
        -9.5200725e-05,  5.4106116e-04, -4.1974443e-03,  7.2709518e-03,
         4.0179468e-03,  4.6291593e-03,  3.3723693e-03,  6.0113193e-04,
         7.0312880e-03, -6.5026758e-04, -5.2520400e-03, -3.4077312e-03,
        -5.7724776e-04, -3.5962556e-04, -1.9444939e-03,  6.7740148e-03,
         1.7657895e-03,  3.0707046e-03,  2.6535376e-03, -1.2252899e-04,
         3.2407520e-03,  8.3062677e-03, -2.9370422e-03, -2.7848519e-03,
         2.9828635e-03, -5.0905012e-03, -1.0488846e-03, -4.2963931e-03,
         2.8095543e-03,  3.5794398e-03,  9.2533138e-03, -4.8739216e-03,
        -7.0769177e-04, -1.0116814e-03, -2.0592390e-03, -3.6049224e-03,
        -3.0606047e-03, -6.7865727e-03,  2.4562173e-03,  5.8957553e-03,
         1.9706071e-03, -1.9286091e-03,  3.9289551e-04,  8.1520341e-04,
        -3.3995372e-03, -1.7364440e-04,  3.6868851e-03,  2.2311849e-03,
         5.4681930e-03, -4.7483412e-03,  1.9319847e-03, -9.2935120e-04,
         2.9744153e-04, -7.2830068e-03, -6.4567300e-03,  5.2810959e-03,
         2.3075573e-03,  4.2308876e-03,  7.4545853e-05,  8.7718824e-03,
        -2.0718365e-03,  2.2364482e-03,  9.8400153e-03, -1.0944766e-03,
        -5.3129308e-03, -1.4531836e-03,  6.1887698e-03, -1.5859664e-03],
       dtype=float32),
 array([-6.6428864e-04,  2.5534418e-03,  6.0415594e-04,  2.8123609e-03,
        -4.6691885e-03, -2.3388788e-03, -1.8680580e-03, -5.8428827e-03,
        -5.0709341e-03, -3.9024856e-03, -2.8914362e-03,  2.9166813e-03,
        -2.5274309e-03, -3.8849046e-03,  4.6318076e-03,  4.7273794e-03,
         6.2756832e-03,  2.1019380e-03, -2.9137714e-03, -7.6386621e-03,
         3.0299968e-03,  4.6484079e-03,  4.5861928e-03, -1.2901195e-03,
         3.0240044e-06,  7.6031350e-03, -6.8486980e-03, -2.4359021e-04,
        -2.6764076e-03,  7.4613239e-03,  4.3687504e-04,  4.4037560e-03,
         3.3017830e-03, -5.9633981e-03,  1.6452797e-03, -2.6288992e-03,
        -7.2626201e-03,  3.9700079e-03, -3.1177320e-03, -6.2821782e-05,
         3.3034931e-03, -3.3070408e-03,  1.9134132e-03,  3.9625932e-03,
         3.0113396e-03, -6.6351518e-03, -5.2364562e-03, -1.6339992e-03,
         7.6353503e-03, -9.8097580e-04, -4.4014710e-03, -2.8466547e-04,
         1.1963283e-03, -2.7402057e-03, -3.3953143e-03,  6.0613416e-03,
        -2.0708572e-03,  1.2286797e-03, -1.0593025e-03,  7.1996339e-03,
         6.6840909e-03,  1.9344456e-03,  2.7122418e-04,  8.7867053e-03,
         4.7772666e-03,  2.5937043e-03, -3.5068626e-04,  7.1064020e-03,
         2.0416067e-03, -3.7206428e-03,  4.8270042e-04, -2.4327389e-03,
        -1.9001353e-03,  3.7627877e-04,  2.3793476e-03,  5.5991523e-03,
         3.2141709e-03,  5.5021862e-04,  3.2286164e-03, -6.1493572e-03,
        -2.3699929e-03, -2.9567597e-03, -2.8376887e-04,  4.1155135e-03,
         2.3938257e-03,  8.8432420e-04,  6.8328679e-03,  8.5155377e-03,
         3.8156663e-03, -4.4763791e-03,  5.2274475e-03,  1.6186496e-03,
        -3.2519461e-03,  2.4727578e-03, -3.9075334e-03, -2.5998722e-03,
         3.4335358e-03, -3.8407512e-03, -1.1309527e-03,  2.8011256e-03],
       dtype=float32),
 array([-1.7291438e-03, -1.4484493e-03, -2.9845778e-03, -9.2889625e-04,
         4.4617872e-03,  3.3064620e-03, -3.2166764e-03,  4.8703896e-03,
        -2.4170147e-03,  7.9002709e-04, -3.4177324e-03, -3.9657806e-03,
         2.2838905e-03, -4.8968446e-05,  1.5955279e-03, -2.9923546e-03,
         3.7601534e-03,  3.2254972e-03, -1.0714582e-03, -4.9363300e-03,
        -4.4459668e-03, -1.0129841e-03, -3.0557951e-03, -2.7640290e-03,
         6.0451198e-03, -1.6727921e-03,  2.3967773e-04,  7.0522949e-03,
        -4.2963242e-03,  2.9766257e-03,  2.9767537e-03, -2.1905219e-03,
        -2.3554270e-03,  1.0841379e-03, -7.7041443e-03, -1.7836521e-03,
        -1.5042694e-03,  7.0105901e-04,  1.6160161e-03,  7.8794023e-04,
        -2.1252851e-03,  4.1639893e-03, -1.8731989e-03,  1.9158964e-03,
        -3.3255623e-04,  4.1560153e-04,  2.1288234e-03, -1.2777511e-03,
        -2.7269924e-03,  2.7286403e-03,  3.0241231e-03, -1.0035043e-03,
        -3.6465044e-03, -3.3865958e-03, -3.2220089e-03, -6.0515413e-03,
        -2.7680895e-03, -2.2451112e-03,  1.4773884e-04, -3.9260779e-04,
        -9.7438233e-04, -1.3198545e-03,  8.4938277e-03,  8.6225686e-04,
        -5.9768450e-03,  3.7012810e-03,  4.9763313e-03,  8.0432277e-05,
        -5.4441919e-03,  2.2586240e-03,  4.2015575e-03,  5.5764169e-03,
         2.1366426e-03, -2.8426955e-03, -1.2876241e-03,  2.4864133e-03,
         6.5889447e-03, -1.0551556e-03, -1.6501792e-03,  2.2593728e-04,
        -6.5171608e-04, -3.4640224e-03, -4.6502417e-03,  4.2941528e-03,
        -3.7127818e-04, -4.4611180e-03, -2.3753254e-03, -4.3805805e-03,
         4.5247651e-03,  1.8487026e-03, -3.8290666e-03,  4.3589883e-03,
         7.2172089e-03, -2.0966630e-03,  7.2753029e-03,  9.9082792e-04,
         2.8618730e-03,  3.1983894e-03,  8.1609292e-03, -6.7521818e-04],
       dtype=float32),
 array([ 1.9035405e-03,  3.9343414e-04,  9.2457852e-04,  3.0172025e-03,
         2.2549902e-03, -2.8967094e-03,  6.8407105e-03,  3.3481538e-03,
        -5.2028052e-03, -2.3854703e-03,  1.5204179e-03, -3.1048281e-03,
         3.1235598e-03,  3.8799229e-03,  2.7888429e-03, -2.2179175e-03,
         2.0679226e-03,  2.5935390e-03,  4.9281790e-04, -4.9833879e-03,
         4.5861844e-03, -9.2246570e-05,  3.1471029e-03, -3.1841241e-03,
         2.8171216e-03, -8.8214257e-04, -3.4540244e-03, -1.6681526e-03,
         5.6218507e-04, -3.6022055e-03,  2.5891352e-03,  1.0472573e-03,
         6.3379837e-04,  3.6597688e-04, -6.5196201e-04,  1.8791009e-03,
        -1.5210793e-03,  1.1290505e-03,  2.0456719e-03, -7.1145333e-03,
         3.3983999e-04, -2.3830358e-03,  2.8341054e-03, -1.9169292e-04,
        -1.3150959e-04,  9.6360513e-04, -5.0056777e-03,  1.4202650e-04,
         1.5156337e-03,  3.4684115e-04, -1.2557458e-03, -3.0111242e-04,
        -1.3939406e-03, -1.1986207e-03,  3.5498911e-03, -1.3181119e-03,
         1.1541263e-03, -2.0750628e-03,  8.7378157e-04, -1.3233893e-04,
        -2.5904682e-03, -9.2858088e-04,  2.7440358e-03,  3.7429979e-04,
        -2.7918173e-03,  3.7950657e-03, -8.5503981e-04,  3.8397647e-03,
        -2.6926356e-03, -7.1543606e-04,  7.0882862e-04,  9.6039183e-04,
         2.4310406e-03,  3.0408972e-03,  4.1106362e-03, -1.9139521e-03,
         2.0272615e-03,  2.0478007e-03, -3.4570280e-03, -5.7184009e-04,
        -1.3991066e-03, -4.8949255e-04,  1.6160170e-03,  3.0870026e-03,
         3.2451819e-03,  2.7347059e-04,  5.4910015e-03, -2.4816203e-03,
        -7.9544133e-04,  8.3426927e-04,  2.0979184e-03,  2.1774853e-04,
         2.7964399e-03,  7.5560331e-04,  5.7594320e-03,  4.9201353e-03,
         7.2148035e-04, -2.0639263e-03,  2.5203465e-03, -6.1635488e-05],
       dtype=float32),
 array([ 1.3016289e-03, -1.3484154e-04, -4.4195974e-04,  7.8035449e-04,
         3.8166158e-03,  3.7197428e-04, -1.0993184e-03,  5.4643978e-03,
        -2.4276960e-03,  1.0803941e-03, -2.0049892e-03, -3.6984068e-04,
        -5.9563816e-03,  2.6207657e-03, -2.6376564e-03, -3.1041494e-04,
        -5.1952316e-03, -3.6273772e-04, -1.2669386e-04, -7.5498843e-03,
         1.6610600e-03, -3.4086660e-03,  4.1034203e-03,  1.8267572e-03,
        -4.1841590e-03,  6.7151897e-04,  3.2460349e-04,  7.6439278e-04,
        -3.1011545e-03, -1.1119301e-04,  2.3427019e-03, -3.1695713e-03,
         1.0426062e-03, -5.5770776e-03,  3.8168896e-03, -2.2460816e-04,
         9.1156224e-04,  8.5732849e-05, -5.7410523e-03, -4.5822212e-03,
        -2.4325552e-03, -5.1791361e-03, -4.9146027e-03,  7.5353286e-03,
         3.8219697e-03, -2.3825355e-03,  1.6449001e-03, -1.8068039e-03,
         3.4968152e-03,  1.8107472e-03,  4.8876595e-04, -2.7975645e-03,
         5.7744142e-03,  1.1712991e-03, -2.1263633e-03, -1.5151765e-03,
        -4.8256055e-03, -4.4335499e-03, -3.2735039e-03, -3.0262175e-03,
         3.7582342e-03, -2.6397698e-04,  1.8845868e-03,  1.0961145e-03,
        -3.1697934e-03,  3.5096221e-03,  2.8127905e-03,  8.4059602e-03,
        -2.3199851e-03,  5.6165420e-03, -6.5233227e-04,  8.0178985e-03,
         1.8757519e-04,  2.1276872e-03,  1.9924769e-03,  1.4016674e-03,
         1.2225099e-04,  3.4493806e-03,  4.5455666e-03, -6.1293668e-03,
        -3.1390076e-03, -2.3701033e-03, -4.5050331e-03, -4.2644865e-03,
        -2.5542451e-03, -2.6186004e-03, -1.7264070e-03, -3.1096544e-03,
        -1.8825332e-03, -8.8143552e-04,  4.9997377e-03, -1.0383318e-03,
         1.5767490e-03,  2.2196034e-03,  1.3951488e-03, -2.1448755e-03,
        -3.6507258e-03, -2.6970310e-04, -3.9575882e-03,  1.6354406e-03],
       dtype=float32),
 array([-4.6001310e-03,  1.0706029e-03, -3.0681491e-04,  1.5245103e-03,
         6.2351432e-03,  5.2267988e-03,  3.2841447e-03,  1.6488093e-03,
        -3.6541740e-03,  3.5123443e-03, -2.9655700e-03, -1.9359845e-03,
         4.1583572e-03, -1.6916526e-03,  9.3889749e-04, -3.7593488e-03,
         1.4689359e-03,  9.9815044e-04, -2.0022003e-03, -4.7017513e-03,
        -4.2873202e-04,  7.5568858e-04,  3.8642238e-03, -3.1775064e-03,
         4.7567952e-04, -9.9171721e-04, -1.6025926e-03,  2.2951006e-03,
        -1.9227592e-03,  3.4294929e-03,  1.8282693e-03, -1.9190797e-03,
         5.4989406e-04,  3.8772384e-03, -4.0736063e-03,  2.8339797e-04,
        -4.7482336e-03,  1.4019179e-03,  1.6451022e-03, -2.2515436e-03,
        -7.4052473e-04,  2.3998534e-03, -1.4660303e-03,  1.0383863e-03,
        -1.6102341e-03, -2.6617281e-03,  4.2991675e-03, -2.7140484e-03,
        -1.7625515e-03,  6.6164524e-05,  2.6638131e-03, -1.4996722e-03,
        -1.6454890e-03, -4.2187427e-03, -1.5769498e-03, -1.9125248e-03,
        -7.3681871e-04, -1.2055491e-03, -1.4880137e-04, -3.4584501e-03,
        -2.9659977e-03, -4.8971153e-03,  6.1553596e-03, -5.6817790e-04,
        -7.3977942e-03,  2.6504388e-03,  4.6505174e-03,  2.0568313e-03,
        -8.2668914e-03,  3.3671469e-03,  1.5749718e-04,  1.8149328e-03,
         3.3112529e-03,  7.5968984e-04, -3.5795451e-03, -1.9285125e-03,
         3.7605104e-03, -2.1026265e-03, -5.7165986e-03,  1.3581389e-03,
        -1.9419445e-03, -6.8664318e-04, -8.5611711e-04,  4.5920769e-03,
         4.1400071e-04, -2.7154754e-03, -2.1979178e-04, -2.2907092e-03,
         4.2984466e-04,  1.7682861e-03,  3.8704579e-04, -5.0182478e-04,
         4.1925590e-03, -5.3663817e-03,  3.6659152e-03,  1.4089709e-03,
         5.2357083e-03,  4.0766052e-03,  6.6363746e-03, -5.4453051e-04],
       dtype=float32),
 array([ 3.06412554e-03,  3.53955384e-03, -1.48396633e-04,  1.41619204e-03,
        -6.97404437e-04,  2.05248594e-04, -1.19311002e-03,  5.81200467e-03,
        -3.67548014e-03,  2.06005317e-03, -1.50419027e-03,  1.26904261e-03,
         1.74993742e-03,  2.42073252e-03, -2.15908489e-03, -1.27641729e-03,
         4.94069047e-03,  6.09304337e-03, -7.73280347e-03, -7.52251083e-03,
        -1.74604042e-03, -1.27052888e-04, -1.76810136e-03, -5.33280335e-03,
         4.12652129e-03, -2.37016589e-03, -6.75499439e-04,  2.42639589e-03,
        -4.48993547e-03,  2.27627694e-03, -8.56945626e-05, -2.99422839e-03,
        -1.77725533e-03, -5.52701764e-03, -3.88709363e-03,  1.32698298e-03,
         4.37984290e-03, -1.37707312e-03,  8.77399696e-04, -5.09727886e-03,
        -5.52171888e-03,  6.88145403e-04, -1.29006745e-03,  2.50227749e-05,
        -2.56248750e-04, -1.74984464e-03, -2.49164202e-03, -9.81360208e-05,
        -3.34822427e-04,  1.38779730e-03, -3.03430762e-03, -4.68340615e-04,
        -6.45552622e-03, -2.73753027e-03,  3.53874319e-04, -4.81845206e-03,
        -1.65629305e-03, -4.91950801e-03, -6.36783661e-03,  1.64129946e-03,
         2.87877652e-03, -2.12472491e-03,  2.48076278e-03, -3.82854952e-04,
        -1.00798905e-04,  5.85808605e-03,  5.40694268e-03,  4.75091860e-04,
        -5.86008094e-03,  4.43690311e-04,  6.77879900e-04,  1.87584583e-03,
        -1.65868911e-03, -3.40285501e-03,  8.78533057e-04,  2.01268704e-03,
         2.76906672e-03,  2.66542309e-03, -1.51447486e-03, -1.39291224e-03,
         2.52325158e-03,  6.61030121e-04, -1.22052978e-03,  3.49885249e-03,
        -3.20232497e-03, -6.68840483e-04,  1.97128090e-03, -7.51956366e-04,
         6.78469427e-04,  3.25699989e-03, -2.85673514e-03,  1.23522175e-03,
         6.93688774e-03, -2.58935173e-03,  5.48397563e-03,  3.86503671e-04,
        -4.17771330e-03,  7.66240351e-04,  1.14069181e-03,  1.47960987e-03],
       dtype=float32),
 array([-3.8170654e-03,  6.8870722e-05, -1.2497066e-03, -2.2227889e-04,
        -3.1874313e-03, -3.1269214e-03,  3.7064489e-03,  4.6344483e-03,
        -2.9569704e-03, -3.5221216e-03,  2.0344069e-03,  1.0113992e-03,
        -2.8112563e-03,  6.4130605e-04, -2.3399605e-03, -5.8445882e-04,
         2.4570248e-03,  1.8827431e-04, -2.1832616e-03, -4.3643536e-03,
        -8.9923345e-04, -6.5515708e-04,  4.1148923e-03,  4.4834963e-03,
        -1.4596239e-03, -1.6543756e-03,  6.6314550e-04,  2.3527151e-04,
        -1.8846877e-03, -1.4782082e-03,  4.4256155e-03,  1.5116844e-03,
         6.3654326e-04, -1.2806632e-03,  2.1927763e-05,  1.5620989e-03,

In [67]:
x_new[0]

array([ 4.90587484e-03,  7.42763234e-03, -4.90260951e-04, -2.57627969e-03,
        8.43458436e-03, -1.65554741e-03,  6.02112757e-03, -1.17452419e-03,
        8.13173782e-03, -2.30359752e-03,  7.14591984e-03, -9.59941465e-03,
       -3.66904307e-03, -2.94727972e-03, -5.68767125e-03,  3.36751807e-04,
        7.76648615e-03, -5.07516600e-03, -7.29449908e-04,  2.24450231e-03,
        4.31937864e-04,  7.20499735e-03,  3.29957664e-04,  3.88500863e-04,
       -5.12075657e-03, -3.30026960e-04, -3.74833355e-03, -1.61338085e-03,
        1.36708189e-03, -3.56327882e-03, -5.17212786e-04, -4.94958740e-03,
       -3.09191109e-03, -5.95131144e-03, -6.04506768e-03, -8.66895169e-03,
        4.05815523e-03,  8.43399670e-03,  3.86941223e-03,  1.04526314e-03,
       -9.09166411e-05, -1.52226270e-03, -1.32536166e-03, -6.50381437e-04,
       -4.33369307e-04,  5.13917813e-03, -6.15554117e-03, -4.69092047e-04,
        1.58127863e-03,  4.77538817e-03,  6.42391504e-04, -2.33718567e-03,
        4.90518939e-03, -7.17275776e-03,  8.50535231e-04, -2.63266219e-03,
        9.24899802e-03,  3.26875341e-03, -8.28719058e-04,  5.29996678e-03,
       -7.36241415e-03, -7.34253321e-03,  3.43329879e-03,  1.97892962e-03,
       -1.17403921e-04,  2.04697973e-03, -5.93184587e-03, -1.54166331e-03,
       -4.25411679e-04, -3.08493292e-03, -1.50784757e-03, -1.54684274e-03,
        6.43881690e-03, -4.50006500e-03, -3.43749602e-03, -8.29754770e-03,
        1.95944216e-04, -1.42864219e-03,  2.48848111e-04, -2.86015566e-03,
       -6.38118479e-03, -2.55876861e-04,  4.65841545e-03, -3.49784573e-03,
        6.63580280e-03, -2.94285594e-03,  1.46373478e-03,  2.12078006e-03,
        2.88387039e-03, -3.02826054e-03,  4.31863777e-03,  1.59578642e-03,
        4.06069867e-03, -1.50721427e-03,  2.58495566e-03, -3.32017895e-04,
        2.64044548e-03,  6.35247864e-03, -7.09227612e-03,  2.68909591e-03])

In [44]:
x_new[0].shape

(100,)

In [45]:
## dependent features
## output features
y=pd.get_dummies(messages['label'])
y=y.iloc[:,0].values

In [46]:
messages

    label                                            message
0     ham  Go until jurong point, crazy.. Available only ...
1     ham                        Ok lar... Joking wif u oni.
2    spam  Free entry in 2 a wkly comp to win FA Cup fina...
3     ham    U dun say so early hor... U c already then say.
4     ham  Nah I don't think he goes to usf, he lives aro...
..    ...                                                ...
98   spam                  Last chance to claim your reward.
99    ham                  Can you share the lecture slides?
100  spam               You have won ₹50,000 cash. Call now.
101   ham                       Good night and sweet dreams.
102  spam     Free gift waiting for you. Text GIFT to 77777.

[103 rows x 2 columns]

In [47]:
messages.shape

(103, 2)

In [69]:
x[0]

array([ 4.9058748e-03,  7.4276323e-03, -4.9026095e-04, -2.5762797e-03,
        8.4345844e-03, -1.6555474e-03,  6.0211276e-03, -1.1745242e-03,
        8.1317378e-03, -2.3035975e-03,  7.1459198e-03, -9.5994147e-03,
       -3.6690431e-03, -2.9472797e-03, -5.6876712e-03,  3.3675181e-04,
        7.7664861e-03, -5.0751660e-03, -7.2944991e-04,  2.2445023e-03,
        4.3193786e-04,  7.2049974e-03,  3.2995766e-04,  3.8850086e-04,
       -5.1207566e-03, -3.3002696e-04, -3.7483335e-03, -1.6133809e-03,
        1.3670819e-03, -3.5632788e-03, -5.1721279e-04, -4.9495874e-03,
       -3.0919111e-03, -5.9513114e-03, -6.0450677e-03, -8.6689517e-03,
        4.0581552e-03,  8.4339967e-03,  3.8694122e-03,  1.0452631e-03,
       -9.0916641e-05, -1.5222627e-03, -1.3253617e-03, -6.5038144e-04,
       -4.3336931e-04,  5.1391781e-03, -6.1555412e-03, -4.6909205e-04,
        1.5812786e-03,  4.7753882e-03,  6.4239150e-04, -2.3371857e-03,
        4.9051894e-03, -7.1727578e-03,  8.5053523e-04, -2.6326622e-03,
        9.2489980e-03,  3.2687534e-03, -8.2871906e-04,  5.2999668e-03,
       -7.3624142e-03, -7.3425332e-03,  3.4332988e-03,  1.9789296e-03,
       -1.1740392e-04,  2.0469797e-03, -5.9318459e-03, -1.5416633e-03,
       -4.2541168e-04, -3.0849329e-03, -1.5078476e-03, -1.5468427e-03,
        6.4388169e-03, -4.5000650e-03, -3.4374960e-03, -8.2975477e-03,
        1.9594422e-04, -1.4286422e-03,  2.4884811e-04, -2.8601557e-03,
       -6.3811848e-03, -2.5587686e-04,  4.6584154e-03, -3.4978457e-03,
        6.6358028e-03, -2.9428559e-03,  1.4637348e-03,  2.1207801e-03,
        2.8838704e-03, -3.0282605e-03,  4.3186378e-03,  1.5957864e-03,
        4.0606987e-03, -1.5072143e-03,  2.5849557e-03, -3.3201789e-04,
        2.6404455e-03,  6.3524786e-03, -7.0922761e-03,  2.6890959e-03],
      dtype=float32)

In [71]:
df = pd.DataFrame()
for i in range(len(x)):
    row = pd.DataFrame(x[i].reshape(1, -1))
    df = pd.concat([df, row], ignore_index=True)

In [72]:
df.shape

(103, 100)

In [73]:
x[0].shape

(100,)

In [75]:
x[0].reshape(1,-1).shape

(1, 100)

In [77]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,0.004906,0.007428,-0.000490,-0.002576,0.008435,-0.001656,0.006021,-0.001175,0.008132,-0.002304,...,0.004319,0.001596,0.004061,-0.001507,0.002585,-0.000332,0.002640,0.006352,-0.007092,0.002689
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.002612,0.003235,0.003095,0.001204,-0.003315,0.000640,0.005708,-0.000166,0.000179,-0.006746,...,0.001571,0.000630,-0.005350,0.004413,-0.000109,-0.003154,-0.002327,-0.000338,0.001922,0.001026
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.008165,-0.004443,0.008982,0.008260,-0.004435,0.000299,0.004276,-0.003921,-0.005566,-0.006517,...,0.002055,-0.004002,-0.008240,0.006281,-0.001940,-0.000673,-0.001772,-0.004535,0.004068,-0.004267

In [78]:
## independent feature
x=df

In [79]:
## train test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)

In [80]:
x_train.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
86,0.001931,-0.001269,0.000420,0.005517,0.000892,-0.002123,0.006300,0.003444,-0.005498,-0.001808,...,0.000339,-0.000626,0.001855,0.001847,0.005499,0.004340,0.001433,-0.002113,0.002246,0.001683
0,0.004906,0.007428,-0.000490,-0.002576,0.008435,-0.001656,0.006021,-0.001175,0.008132,-0.002304,...,0.004319,0.001596,0.004061,-0.001507,0.002585,-0.000332,0.002640,0.006352,-0.007092,0.002689
51,-0.002254,0.005192,0.000944,0.002182,-0.001798,-0.004469,-0.001704,0.003268,-0.002530,-0.001871,...,0.001355,0.000915,0.003889,-0.003222,-0.000025,-0.001524,-0.001104,-0.000936,-0.005158,0.006457
19,0.005576,0.008260,0.004085,-0.002529,0.002945,-0.000302,0.001927,0.002606,0.006619,-0.004004,...,0.007939,-0.001188,0.003427,0.003400,-0.000845,-0.004545,-0.001754,0.008530,-0.005996,0.007521
24,-0.002119,0.006469,-0.001359,-0.003436,0.006661,-0.000917,0.002699,0.004194,-0.002107,-0.002006,...,-0.000925,0.002746,0.004988,-0.003421,0.008159,0.004055,0.003209,-0.002944,0.003112,-0.006533

In [81]:
y_train

array([False,  True,  True,  True, False, False, False,  True, False,
        True, False, False, False,  True,  True, False,  True,  True,
        True,  True, False, False, False, False, False, False, False,
        True,  True,  True, False, False,  True,  True,  True,  True,
       False, False,  True, False, False,  True,  True, False,  True,
        True, False,  True, False,  True,  True,  True, False, False,
       False,  True,  True, False,  True, False, False,  True,  True,
        True, False,  True, False,  True, False,  True,  True,  True,
       False, False, False, False,  True, False, False, False,  True,
        True])

In [82]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()

In [83]:
classifier.fit(x_train,y_train)

RandomForestClassifier()

In [85]:
x.isnull().sum()

0     0
1     0
2     0
3     0
4     0
     ..
95    0
96    0
97    0
98    0
99    0
Length: 100, dtype: int64

In [86]:
df['Output'] = y

In [87]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,Output
0,0.004906,0.007428,-0.000490,-0.002576,0.008435,-0.001656,0.006021,-0.001175,0.008132,-0.002304,...,0.001596,0.004061,-0.001507,0.002585,-0.000332,0.002640,0.006352,-0.007092,0.002689,True
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
2,0.002612,0.003235,0.003095,0.001204,-0.003315,0.000640,0.005708,-0.000166,0.000179,-0.006746,...,0.000630,-0.005350,0.004413,-0.000109,-0.003154,-0.002327,-0.000338,0.001922,0.001026,False
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
4,0.008165,-0.004443,0.008982,0.008260,-0.004435,0.000299,0.004276,-0.003921,-0.005566,-0.006517,...,-0.004002,-0.008240,0.006281,-0.001940,-0.000673,-0.001772,-0.004535,0.004068,-0.004267,True

In [88]:
df.dropna(inplace=True)

In [89]:
df.isnull().sum()

0         0
1         0
2         0
3         0
4         0
         ..
96        0
97        0
98        0
99        0
Output    0
Length: 101, dtype: int64

In [90]:
y=df['Output']

In [91]:
y_pred=classifier.predict(x_test)

In [92]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))

0.7619047619047619

In [93]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       0.75      0.67      0.71         9
        True       0.77      0.83      0.80        12

    accuracy                           0.76        21
   macro avg       0.76      0.75      0.75        21
weighted avg       0.76      0.76      0.76        21